package agents

import (
	"log"
	"math"
	"sort"
	"time"

	"bnf_go_engine/config"
	"bnf_go_engine/core"
	"bnf_go_engine/data"
)

// Signal represents a trade signal generated by a strategy scan
type Signal struct {
	Strategy        string
	Symbol          string
	Token           uint32
	Regime          string
	EntryPrice      float64
	StopPrice       float64
	PartialTarget   float64
	TargetPrice     float64
	ATR             float64
	ADX             float64
	RVol            float64
	RSI             float64
	VWAP            float64
	Product         string
	IsShort         bool
	MaxHoldMins     int
	SortKey         float64
	ExpectedNetPnL  float64 // Expected net profit after charges at target
	EstCharges      float64 // Estimated round-trip charges
	Qty             int     // Pre-computed quantity from position sizing
}

// ScannerAgent — exact port of Python scanner_agent.py
type ScannerAgent struct {
	// Data references (will be set by engine)
	Universe     map[uint32]string   // token -> symbol
	GetLTP       func(uint32) float64
	GetVWAP      func(uint32) float64
	GetVolume    func(uint32) int64
	GetDepth     func(uint32) map[string]float64
	GetCandles5m func(uint32) []Candle
	GetORB       func(uint32) (float64, float64) // high, low
	DailyCache   *DailyCache
	ComputeRVol  func(uint32) float64
	GetIntraday  func(uint32, string) []Candle
	GetIndiaVIX  func() float64
	GetADRatio   func() float64
	GetDayOpen   func(uint32) float64

	// Cooldown tracking
	s6Cooldown       map[string]time.Time
	s3TradesToday    int
	s3TradeDate      time.Time
	dailyTradeCount  int
	dailyTradeDate   time.Time
	s6vTradesToday   int
	s6vTradeDate     time.Time
	s6vLastLossTime  time.Time
	symbolCooldown   map[string]int
	dailyPnl         float64
	dailyPnlDate     time.Time
	LastRegime       string // Shared regime for both main loop and API
}

// Candle represents OHLCV data
type Candle struct {
	Open   float64
	High   float64
	Low    float64
	Close  float64
	Volume int64
}

// DailyCache mocks the precomputed daily cache
type DailyCache struct {
	SMA200  map[uint32]float64
	ATR     map[uint32]float64
	EMA25   map[uint32]float64
	BBLower map[uint32]float64
	Closes  map[uint32][]float64
	Highs   map[uint32][]float64
	Lows    map[uint32][]float64
	AvgVol  map[uint32]float64
	TurnoverCr map[uint32]float64
	PivotSupport map[uint32]float64
	Loaded  bool
}

func NewScannerAgent() *ScannerAgent {
	return &ScannerAgent{
		s6Cooldown:     make(map[string]time.Time),
		symbolCooldown: make(map[string]int),
	}
}

// ── Regime Detection ─────────────────────────────────────────
func (s *ScannerAgent) DetectRegime() string {
	vix := 16.0
	if s.GetIndiaVIX != nil {
		v := s.GetIndiaVIX()
		if v > 0 {
			vix = v
		}
	}

	result := "UNKNOWN"
	adRatio := 0.5
	if s.GetADRatio != nil {
		a := s.GetADRatio()
		if a > 0 {
			adRatio = a
		}
	}

	aboveEMA := false
	if s.DailyCache != nil && s.DailyCache.Loaded {
		ema25 := s.DailyCache.EMA25[config.Nifty50Token]
		niftyLTP := 0.0
		if s.GetLTP != nil {
			niftyLTP = s.GetLTP(config.Nifty50Token)
		}
		aboveEMA = niftyLTP > ema25 && niftyLTP > 0
	}

	if vix >= config.VIXExtremeStop {
		result = "EXTREME_PANIC"
	} else if vix > config.VIXBearPanic && !aboveEMA && adRatio < 0.40 {
		log.Printf("[Regime] BEAR_PANIC — VIX=%.1f AD=%.2f", vix, adRatio)
		result = "BEAR_PANIC"
	} else if vix < config.VIXBearPanic && aboveEMA && adRatio > 0.60 {
		log.Printf("[Regime] BULL — VIX=%.1f AD=%.2f", vix, adRatio)
		result = "BULL"
	} else if config.VIXBullMax <= vix && vix < config.VIXExtremeStop {
		log.Printf("[Regime] VOLATILE — VIX=%.1f AD=%.2f", vix, adRatio)
		result = "VOLATILE"
	} else if config.VIXNormalLow <= vix && vix < config.VIXBullMax {
		log.Printf("[Regime] NORMAL — VIX=%.1f AD=%.2f", vix, adRatio)
		result = "NORMAL"
	} else {
		log.Printf("[Regime] CHOP — VIX=%.1f AD=%.2f", vix, adRatio)
		result = "CHOP"
	}

	s.LastRegime = result
	return result
}

// ── Time Enforcement ─────────────────────────────────────────
func (s *ScannerAgent) IsInTradeWindow() bool {
	now := config.NowIST()
	t := now.Hour()*100 + now.Minute()
	sh, sm := config.ParseTime(config.TradeWindowStart)
	eh, em := config.ParseTime(config.TradeWindowEnd)
	start := sh*100 + sm
	end := eh*100 + em
	return t >= start && t <= end
}

func (s *ScannerAgent) checkDailyTradeLimit() bool {
	if s.CircuitBreakerTripped() {
		return false
	}
	today := config.TodayIST()
	if !s.dailyTradeDate.Equal(today) {
		s.dailyTradeCount = 0
		s.dailyTradeDate = today
	}
	return s.dailyTradeCount < config.MaxTradesPerDay
}

func (s *ScannerAgent) RegisterTrade() {
	today := config.TodayIST()
	if !s.dailyTradeDate.Equal(today) {
		s.dailyTradeCount = 0
		s.dailyTradeDate = today
	}
	s.dailyTradeCount++
}

func (s *ScannerAgent) CircuitBreakerTripped() bool {
	return s.dailyPnl < -(config.TotalCapital * config.DailyLossLimitPct)
}

func (s *ScannerAgent) RecordPnl(pnl float64) {
	s.dailyPnl += pnl
}

func (s *ScannerAgent) NewSession() {
	s.dailyPnl = 0
	s.s6vTradesToday = 0
	s.s6vLastLossTime = time.Time{}

	expired := []string{}
	for k, v := range s.symbolCooldown {
		if v <= 1 {
			expired = append(expired, k)
		}
	}
	for _, k := range expired {
		delete(s.symbolCooldown, k)
	}
	for k := range s.symbolCooldown {
		s.symbolCooldown[k]--
	}
}

func (s *ScannerAgent) cacheReady() bool {
	return s.DailyCache != nil && s.DailyCache.Loaded && s.GetLTP != nil
}

// GetCurrentVIX returns current India VIX value for ML filter
func (s *ScannerAgent) GetCurrentVIX() float64 {
	if s.GetIndiaVIX != nil {
		return s.GetIndiaVIX()
	}
	return 16.0
}

// GetCurrentADRatio returns current advance-decline ratio for ML filter
func (s *ScannerAgent) GetCurrentADRatio() float64 {
	if s.GetADRatio != nil {
		return s.GetADRatio()
	}
	return 0.5
}

// ── Helpers ──────────────────────────────────────────────────
func (s *ScannerAgent) get15MinCloses(token uint32) []float64 {
	candles := s.getCandles5m(token)
	if len(candles) < 3 {
		return nil
	}
	var closes []float64
	for i := 2; i < len(candles); i += 3 {
		closes = append(closes, candles[i].Close)
	}
	return closes
}

func (s *ScannerAgent) get15MinOHLC(token uint32) []Candle {
	candles := s.getCandles5m(token)
	var bars []Candle
	for i := 0; i+2 < len(candles); i += 3 {
		group := candles[i : i+3]
		h := group[0].High
		l := group[0].Low
		var vol int64
		for _, c := range group {
			if c.High > h { h = c.High }
			if c.Low < l { l = c.Low }
			vol += c.Volume
		}
		bars = append(bars, Candle{
			Open: group[0].Open, High: h, Low: l, Close: group[2].Close, Volume: vol,
		})
	}
	return bars
}

func (s *ScannerAgent) getCandles5m(token uint32) []Candle {
	if s.GetCandles5m != nil {
		return s.GetCandles5m(token)
	}
	return nil
}

func (s *ScannerAgent) checkOrderBook(token uint32, isShort bool) bool {
	if s.GetDepth == nil {
		return true
	}
	depth := s.GetDepth(token)
	if depth == nil {
		return true
	}
	ratio := depth["bid_ask_ratio"]
	if isShort && ratio > 2.0 {
		return false
	}
	if !isShort && ratio < 0.5 {
		return false
	}
	return true
}

// ══════════════════════════════════════════════════════════════
//  S1: MA CROSSOVER
// ══════════════════════════════════════════════════════════════
func (s *ScannerAgent) ScanS1(regime string) []*Signal {
	if !s.IsInTradeWindow() || !s.checkDailyTradeLimit() || regime == "EXTREME_PANIC" || !s.cacheReady() {
		return nil
	}

	var signals []*Signal
	for token, symbol := range s.Universe {
		current := s.GetLTP(token)
		if current <= 0 {
			continue
		}

		sma200 := s.DailyCache.SMA200[token]
		if sma200 <= 0 {
			continue
		}
		isAbove200 := current > sma200

		c15 := s.get15MinCloses(token)
		if len(c15) < config.S1_EMA_SLOW+2 {
			continue
		}

		ema9 := data.ComputeEMA(c15, config.S1_EMA_FAST)
		ema21 := data.ComputeEMA(c15, config.S1_EMA_SLOW)
		if len(ema9) < 2 || len(ema21) < 2 {
			continue
		}

		ema9Now, ema9Prev := ema9[len(ema9)-1], ema9[len(ema9)-2]
		ema21Now, ema21Prev := ema21[len(ema21)-1], ema21[len(ema21)-2]

		crossUp := ema9Prev <= ema21Prev && ema9Now > ema21Now
		crossDown := ema9Prev >= ema21Prev && ema9Now < ema21Now

		if !crossUp && !crossDown {
			continue
		}

		rvol := s.computeRVol(token)
		if rvol < 1.2 {
			continue
		}

		candles := s.get15MinOHLC(token)
		if len(candles) < config.S1_ADX_PERIOD+2 {
			continue
		}

		highs := make([]float64, len(candles))
		lows := make([]float64, len(candles))
		closes := make([]float64, len(candles))
		for i, c := range candles {
			highs[i] = c.High
			lows[i] = c.Low
			closes[i] = c.Close
		}

		adx := data.ComputeADX(highs, lows, closes, config.S1_ADX_PERIOD)
		if adx < float64(config.S1_ADX_MIN) {
			continue
		}

		// ATR
		var atrVals []float64
		for i := 1; i < len(highs); i++ {
			tr := math.Max(highs[i]-lows[i], math.Max(math.Abs(highs[i]-closes[i-1]), math.Abs(lows[i]-closes[i-1])))
			atrVals = append(atrVals, tr)
		}
		atr := current * 0.015
		if len(atrVals) >= 14 {
			sum := 0.0
			for _, v := range atrVals[len(atrVals)-14:] {
				sum += v
			}
			atr = sum / 14.0
		}

		// EMA21 slope
		ema21SlopeUp := false
		ema21SlopeDown := false
		if len(ema21) >= 4 {
			ema21SlopeUp = ema21[len(ema21)-1] > ema21[len(ema21)-3]
			ema21SlopeDown = ema21[len(ema21)-1] < ema21[len(ema21)-3]
		}

		if crossUp && isAbove200 && ema21SlopeUp {
			stopPrice := math.Round((current-config.S1_ATR_SL_MULT*atr)*100) / 100
			risk := current - stopPrice
			if risk <= 0 {
				continue
			}
			targetPrice := math.Round((current+config.S1_RR*risk)*100) / 100
			signals = append(signals, &Signal{
				Strategy: "S1_MA_CROSS", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice,
				PartialTarget: math.Round((current+1.0*risk)*100) / 100,
				TargetPrice: targetPrice, ATR: atr, ADX: adx, RVol: rvol,
				Product: "MIS", IsShort: false, SortKey: adx,
			})
		} else if crossDown && !isAbove200 && ema21SlopeDown {
			stopPrice := math.Round((current+config.S1_ATR_SL_MULT*atr)*100) / 100
			risk := stopPrice - current
			if risk <= 0 {
				continue
			}
			targetPrice := math.Round((current-config.S1_RR*risk)*100) / 100
			signals = append(signals, &Signal{
				Strategy: "S1_MA_CROSS", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice,
				PartialTarget: math.Round((current-1.0*risk)*100) / 100,
				TargetPrice: targetPrice, ATR: atr, ADX: adx, RVol: rvol,
				Product: "MIS", IsShort: true, SortKey: adx,
			})
		}
	}

	sort.Slice(signals, func(i, j int) bool { return signals[i].SortKey > signals[j].SortKey })
	if len(signals) > 3 {
		signals = signals[:3]
	}
	return signals
}

// ══════════════════════════════════════════════════════════════
//  S2: BB + RSI MEAN REVERSION
// ══════════════════════════════════════════════════════════════
func (s *ScannerAgent) ScanS2(regime string) []*Signal {
	if !s.IsInTradeWindow() || !s.checkDailyTradeLimit() || regime == "EXTREME_PANIC" || !s.cacheReady() {
		return nil
	}
	vix := 16.0
	if s.GetIndiaVIX != nil {
		vix = s.GetIndiaVIX()
	}
	if vix > config.S2_VIX_MAX {
		return nil
	}

	var signals []*Signal
	for token, symbol := range s.Universe {
		current := s.GetLTP(token)
		if current <= 0 {
			continue
		}

		candles := s.getCandles5m(token)
		if len(candles) < config.S2_BB_PERIOD {
			continue
		}
		closes := make([]float64, len(candles))
		for i, c := range candles {
			closes[i] = c.Close
		}

		bbHi, bbMid, bbLo := data.ComputeBollinger(closes, config.S2_BB_PERIOD, config.S2_BB_SD)
		rsiSlice := data.ComputeRSI(closes, config.S2_RSI_PERIOD)
		rsiVal := rsiSlice[len(rsiSlice)-1]

		vwap := 0.0
		if s.GetVWAP != nil {
			vwap = s.GetVWAP(token)
		}
		if vwap <= 0 {
			continue
		}
		vwapDev := (current - vwap) / vwap

		atr := s.DailyCache.ATR[token]
		if atr <= 0 {
			atr = current * 0.015
		}

		rvol := s.computeRVol(token)
		if rvol < 1.2 {
			continue
		}

		if len(candles) < 2 {
			continue
		}
		prevCandle := candles[len(candles)-2]
		currCandle := candles[len(candles)-1]

		sma200 := s.DailyCache.SMA200[token]

		// LONG
		if prevCandle.Close < bbLo && currCandle.Close > bbLo && rsiVal < float64(config.S2_RSI_OVERSOLD) && vwapDev > -0.03 && (sma200 <= 0 || current >= sma200) {
			stopPrice := math.Round((current-config.S2_ATR_SL_MULT*atr)*100) / 100
			targetPrice := math.Round(bbMid*100) / 100
			risk := current - stopPrice
			if targetPrice <= current*1.001 {
				targetPrice = math.Round((current+config.S2_RR*(current-stopPrice))*100) / 100
			}
			signals = append(signals, &Signal{
				Strategy: "S2_BB_MEAN_REV", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice,
				PartialTarget: math.Round((current+1.0*risk)*100) / 100,
				TargetPrice: targetPrice, RSI: rsiVal, VWAP: vwap, ATR: atr,
				Product: "MIS", IsShort: false, MaxHoldMins: config.S2_MAX_HOLD_MINS,
				SortKey: math.Abs(rsiVal - 50),
			})
		}

		// SHORT
		if prevCandle.Close > bbHi && currCandle.Close < bbHi && rsiVal > float64(config.S2_RSI_OVERBOUGHT) && vwapDev < 0.03 {
			stopPrice := math.Round((current+config.S2_ATR_SL_MULT*atr)*100) / 100
			targetPrice := math.Round(bbMid*100) / 100
			risk := stopPrice - current
			if targetPrice >= current*0.999 {
				targetPrice = math.Round((current-config.S2_RR*(stopPrice-current))*100) / 100
			}
			signals = append(signals, &Signal{
				Strategy: "S2_BB_MEAN_REV", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice,
				PartialTarget: math.Round((current-1.0*risk)*100) / 100,
				TargetPrice: targetPrice, RSI: rsiVal, VWAP: vwap, ATR: atr,
				Product: "MIS", IsShort: true, MaxHoldMins: config.S2_MAX_HOLD_MINS,
				SortKey: math.Abs(rsiVal - 50),
			})
		}
	}

	sort.Slice(signals, func(i, j int) bool { return signals[i].SortKey > signals[j].SortKey })
	if len(signals) > 3 {
		signals = signals[:3]
	}
	return signals
}

// ══════════════════════════════════════════════════════════════
//  S3: OPENING RANGE BREAKOUT
// ══════════════════════════════════════════════════════════════
func (s *ScannerAgent) ScanS3(regime string) []*Signal {
	if !s.IsInTradeWindow() || regime == "EXTREME_PANIC" || !s.checkDailyTradeLimit() || !s.cacheReady() {
		return nil
	}

	today := config.TodayIST()
	if !s.s3TradeDate.Equal(today) {
		s.s3TradesToday = 0
		s.s3TradeDate = today
	}
	if s.s3TradesToday >= 5 {
		return nil
	}

	var signals []*Signal
	for token, symbol := range s.Universe {
		current := s.GetLTP(token)
		if current <= 0 || current < 800 {
			continue
		}

		rvol := s.computeRVol(token)
		if rvol < 1.5 {
			continue
		}

		orbHigh, orbLow := 0.0, 0.0
		if s.GetORB != nil {
			orbHigh, orbLow = s.GetORB(token)
		}
		if orbHigh <= 0 || orbLow <= 0 {
			continue
		}

		atr := s.DailyCache.ATR[token]
		if atr <= 0 {
			atr = current * 0.015
		}

		// LONG
		if current > orbHigh+atr*0.3 {
			if !s.checkOrderBook(token, false) {
				continue
			}
			stopPrice := math.Round((orbLow-atr*0.2)*100) / 100
			risk := current - stopPrice
			if risk <= 0 {
				continue
			}
			targetPrice := math.Round((current+2.5*risk)*100) / 100
			signals = append(signals, &Signal{
				Strategy: "S3_ORB", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
				RVol: rvol, Product: "MIS", IsShort: false, SortKey: rvol,
			})
		}

		// SHORT
		if current < orbLow-atr*0.3 {
			if !s.checkOrderBook(token, true) {
				continue
			}
			stopPrice := math.Round((orbHigh+atr*0.2)*100) / 100
			risk := stopPrice - current
			if risk <= 0 {
				continue
			}
			targetPrice := math.Round((current-2.5*risk)*100) / 100
			signals = append(signals, &Signal{
				Strategy: "S3_ORB", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
				RVol: rvol, Product: "MIS", IsShort: true, SortKey: rvol,
			})
		}
	}

	// NOTE: s3TradesToday is incremented in Execute(), not here.
	// Counting on generation causes rejected signals to consume the daily limit.

	sort.Slice(signals, func(i, j int) bool { return signals[i].SortKey > signals[j].SortKey })
	if len(signals) > 1 {
		signals = signals[:1]
	}
	return signals
}

// ══════════════════════════════════════════════════════════════
//  S6 VWAP BAND
// ══════════════════════════════════════════════════════════════
func (s *ScannerAgent) ScanS6VWAP(regime string) []*Signal {
	if !s.IsInTradeWindow() || !s.checkDailyTradeLimit() || regime == "EXTREME_PANIC" || !s.cacheReady() {
		return nil
	}

	var signals []*Signal
	for token, symbol := range s.Universe {
		current := s.GetLTP(token)
		if current <= 0 || current < 400 {
			continue
		}

		turnover := s.DailyCache.TurnoverCr[token]
		if turnover < 40 {
			continue
		}

		vwap := 0.0
		if s.GetVWAP != nil {
			vwap = s.GetVWAP(token)
		}
		if vwap <= 0 {
			continue
		}

		candles := s.getCandles5m(token)
		if len(candles) < 20 {
			continue
		}
		closes := make([]float64, len(candles))
		for i, c := range candles {
			closes[i] = c.Close
		}

		_, _, vwapSD := data.ComputeBollinger(closes[len(closes)-20:], 20, config.S6_VWAP_SD)
		if vwapSD <= 0 {
			vwapSD = current * 0.008
		}

		rvol := s.computeRVol(token)
		if rvol < 1.2 {
			continue
		}

		rsiSlice := data.ComputeRSI(closes, 14)
		rsi := rsiSlice[len(rsiSlice)-1]

		// LONG
		if current < vwap-1.8*vwapSD && rsi < 35 {
			stopPrice := math.Round((current-1.2*vwapSD)*100) / 100
			risk := current - stopPrice
			if risk <= 0 {
				continue
			}
			targetPrice := math.Round(vwap*100) / 100
			if (targetPrice - current) < 2.0*risk {
				targetPrice = math.Round((current+2.0*risk)*100) / 100
			}
			signals = append(signals, &Signal{
				Strategy: "S6_VWAP_BAND", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
				VWAP: vwap, RVol: rvol, RSI: rsi,
				Product: "MIS", IsShort: false,
				SortKey: math.Abs(current - vwap),
			})
		}

		// SHORT
		if current > vwap+1.8*vwapSD && rsi > 65 {
			stopPrice := math.Round((current+1.2*vwapSD)*100) / 100
			risk := stopPrice - current
			if risk <= 0 {
				continue
			}
			targetPrice := math.Round(vwap*100) / 100
			if (current - targetPrice) < 2.0*risk {
				targetPrice = math.Round((current-2.0*risk)*100) / 100
			}
			signals = append(signals, &Signal{
				Strategy: "S6_VWAP_BAND", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
				VWAP: vwap, RVol: rvol, RSI: rsi,
				Product: "MIS", IsShort: true,
				SortKey: math.Abs(current - vwap),
			})
		}
	}

	sort.Slice(signals, func(i, j int) bool { return signals[i].SortKey > signals[j].SortKey })
	if len(signals) > 2 {
		signals = signals[:2]
	}
	return signals
}

// ══════════════════════════════════════════════════════════════
//  S8: VOLUME PROFILE + PIVOT
// ══════════════════════════════════════════════════════════════
func (s *ScannerAgent) ScanS8(regime string) []*Signal {
	if !s.IsInTradeWindow() || !s.checkDailyTradeLimit() || regime == "EXTREME_PANIC" || !s.cacheReady() {
		return nil
	}

	var signals []*Signal
	for token, symbol := range s.Universe {
		current := s.GetLTP(token)
		if current <= 0 || current < 300 {
			continue
		}

		closes := s.DailyCache.Closes[token]
		highs := s.DailyCache.Highs[token]
		lows := s.DailyCache.Lows[token]
		if len(closes) < 2 || len(highs) < 2 || len(lows) < 2 {
			continue
		}

		// DailyCache.Closes last element = yesterday's close (Kite returns completed bars only)
		// So -1 = yesterday, -2 = day before yesterday
		prevH := highs[len(highs)-1]
		prevL := lows[len(lows)-1]
		prevC := closes[len(closes)-1]
		pivot := (prevH + prevL + prevC) / 3
		r1 := 2*pivot - prevL
		s1 := 2*pivot - prevH
		r2 := pivot + (prevH - prevL)
		s2 := pivot - (prevH - prevL)

		rvol := s.computeRVol(token)
		if rvol < 2.0 {
			continue
		}

		atr := s.DailyCache.ATR[token]
		if atr <= 0 {
			atr = current * 0.015
		}

		candles := s.getCandles5m(token)
		if len(candles) < 2 {
			continue
		}
		currCandle := candles[len(candles)-1]
		prevCandle := candles[len(candles)-2]

		// LONG
		r1Breakout := currCandle.Close > r1
		r1Retest := prevCandle.Close > r1 && currCandle.Low <= r1 && currCandle.Close > r1
		if r1Breakout || r1Retest {
			stopPrice := math.Round((r1-0.15*atr)*100) / 100
			risk := current - stopPrice
			if risk <= 0 {
				stopPrice = math.Round((current-0.5*atr)*100) / 100
				risk = current - stopPrice
			}
			if risk <= 0 {
				continue
			}
			targetPrice := math.Round(r2*100) / 100
			if targetPrice <= current || r2 <= r1 {
				continue
			}
			targetPrice = math.Max(targetPrice, math.Round((current+1.5*risk)*100)/100)

			signals = append(signals, &Signal{
				Strategy: "S8_VOL_PIVOT", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice,
				PartialTarget: math.Round((current+1.0*risk)*100) / 100,
				TargetPrice: targetPrice, RVol: rvol, ATR: atr,
				Product: "MIS", IsShort: false, SortKey: rvol,
			})
		} else {
			// SHORT
			s1Breakdown := currCandle.Close < s1
			s1Retest := prevCandle.Close < s1 && currCandle.High >= s1 && currCandle.Close < s1
			if s1Breakdown || s1Retest {
				stopPrice := math.Round((s1+0.15*atr)*100) / 100
				risk := stopPrice - current
				if risk <= 0 {
					stopPrice = math.Round((current+0.5*atr)*100) / 100
					risk = stopPrice - current
				}
				if risk <= 0 {
					continue
				}
				targetPrice := math.Round(s2*100) / 100
				if targetPrice >= current || s2 <= 0 {
					continue
				}
				targetPrice = math.Min(targetPrice, math.Round((current-1.5*risk)*100)/100)

				signals = append(signals, &Signal{
					Strategy: "S8_VOL_PIVOT", Symbol: symbol, Token: token, Regime: regime,
					EntryPrice: current, StopPrice: stopPrice,
					PartialTarget: math.Round((current-1.0*risk)*100) / 100,
					TargetPrice: targetPrice, RVol: rvol, ATR: atr,
					Product: "MIS", IsShort: true, SortKey: rvol,
				})
			}
		}
	}

	sort.Slice(signals, func(i, j int) bool { return signals[i].SortKey > signals[j].SortKey })
	if len(signals) > 3 {
		signals = signals[:3]
	}
	return signals
}

// ══════════════════════════════════════════════════════════════
//  S9: MULTI-TIMEFRAME MOMENTUM
// ══════════════════════════════════════════════════════════════
func (s *ScannerAgent) ScanS9(regime string) []*Signal {
	if !s.IsInTradeWindow() || regime == "EXTREME_PANIC" || !s.checkDailyTradeLimit() || !s.cacheReady() {
		return nil
	}

	var signals []*Signal
	for token, symbol := range s.Universe {
		current := s.GetLTP(token)
		if current <= 0 || current < 300 {
			continue
		}

		closesD := s.DailyCache.Closes[token]
		if len(closesD) < config.S9_EMA_TREND+5 {
			continue
		}
		ema200Daily := data.ComputeEMA(closesD, config.S9_EMA_TREND)
		isUptrend := current > ema200Daily[len(ema200Daily)-1]

		candles := s.getCandles5m(token)
		if len(candles) < 30 {
			continue
		}
		cCloses := make([]float64, len(candles))
		for i, c := range candles {
			cCloses[i] = c.Close
		}

		macdVal, signalVal, _ := data.ComputeMACD(cCloses, 12, 26, 9)
		macdPrev, signalPrev, _ := data.ComputeMACD(cCloses[:len(cCloses)-1], 12, 26, 9)

		rsiSlice := data.ComputeRSI(cCloses, config.S9_RSI_PERIOD)
		rsi15 := rsiSlice[len(rsiSlice)-1]

		rvol := s.computeRVol(token)
		if regime == "CHOP" && rvol < 1.8 {
			continue
		}
		if rvol < 1.3 {
			continue
		}

		atr := s.DailyCache.ATR[token]
		if atr <= 0 {
			atr = current * 0.02
		}

		// LONG
		if isUptrend && rsi15 > float64(config.S9_RSI_THRESHOLD) && macdPrev < signalPrev && macdVal > signalVal {
			stopPrice := math.Round((current-config.S9_ATR_SL_MULT*atr)*100) / 100
			risk := current - stopPrice
			if risk <= 0 {
				continue
			}
			targetPrice := math.Round((current+config.S9_RR*risk)*100) / 100
			signals = append(signals, &Signal{
				Strategy: "S9_MTF_MOMENTUM", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice,
				PartialTarget: math.Round((current+1.0*risk)*100) / 100,
				TargetPrice: targetPrice, RVol: rvol, ATR: atr, RSI: rsi15,
				Product: "MIS", IsShort: false, SortKey: math.Abs(rsi15 - 50),
			})
		}

		// SHORT
		if !isUptrend && rsi15 < float64(100-config.S9_RSI_THRESHOLD) && macdPrev > signalPrev && macdVal < signalVal {
			stopPrice := math.Round((current+config.S9_ATR_SL_MULT*atr)*100) / 100
			risk := stopPrice - current
			if risk <= 0 {
				continue
			}
			targetPrice := math.Round((current-config.S9_RR*risk)*100) / 100
			signals = append(signals, &Signal{
				Strategy: "S9_MTF_MOMENTUM", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice,
				PartialTarget: math.Round((current-1.0*risk)*100) / 100,
				TargetPrice: targetPrice, RVol: rvol, ATR: atr, RSI: rsi15,
				Product: "MIS", IsShort: true, SortKey: math.Abs(rsi15 - 50),
			})
		}
	}

	sort.Slice(signals, func(i, j int) bool { return signals[i].SortKey > signals[j].SortKey })
	if len(signals) > 3 {
		signals = signals[:3]
	}
	return signals
}

// computeRVol helper
func (s *ScannerAgent) computeRVol(token uint32) float64 {
	if s.ComputeRVol != nil {
		return s.ComputeRVol(token)
	}
	return 0.0
}

// MinNetProfitPerTrade is the minimum expected net profit after ALL charges.
// Trades that can't clear this hurdle are rejected — they create churn, not wealth.
const MinNetProfitPerTrade = 15.0 // Rs. 15 minimum net profit (lowered from 50 to allow scalps)

// FilterByNetProfit rejects signals whose expected profit at target doesn't cover charges.
// This single filter eliminates 60-70% of marginal trades that historically lost money.
func (s *ScannerAgent) FilterByNetProfit(signals []*Signal, capital float64) []*Signal {
	if len(signals) == 0 {
		return nil
	}

	var filtered []*Signal
	for _, sig := range signals {
		// Compute position size (risk-based): risk 0.5% of capital per trade
		risk := math.Abs(sig.EntryPrice - sig.StopPrice)
		if risk <= 0 {
			continue
		}
		maxRiskRs := capital * config.MaxRiskPerTradePct
		qty := int(maxRiskRs / risk)
		if qty <= 0 {
			qty = 1
		}

		// Compute expected gross profit at target
		var grossPnL float64
		if sig.IsShort {
			grossPnL = (sig.EntryPrice - sig.TargetPrice) * float64(qty)
		} else {
			grossPnL = (sig.TargetPrice - sig.EntryPrice) * float64(qty)
		}

		// Compute round-trip charges using centralized Zerodha charge function
		// Includes: brokerage (both sides), STT (sell only), stamp (buy only),
		//           exchange txn, SEBI, GST, IPFT + 0.1% slippage estimate
		totalCharges := core.ComputeChargesFromTrade(
			sig.EntryPrice, sig.TargetPrice, qty, sig.IsShort, "MIS", 0.001)

		netPnL := grossPnL - totalCharges

		if netPnL < MinNetProfitPerTrade {
			log.Printf("[ChargeFilter] REJECT %s %s: gross=%.0f charges=%.0f net=%.0f < min=%.0f (qty=%d)",
				sig.Strategy, sig.Symbol, grossPnL, totalCharges, netPnL, MinNetProfitPerTrade, qty)
			continue
		}

		sig.ExpectedNetPnL = netPnL
		sig.EstCharges = totalCharges
		sig.Qty = qty
		filtered = append(filtered, sig)
	}

	return filtered
}

// ══════════════════════════════════════════════════════════════
//  S10: GAP FILL STRATEGY
//  ~70% of opening gaps fill within 2 hours. One of the highest
//  win rate setups in equity markets.
// ══════════════════════════════════════════════════════════════
func (s *ScannerAgent) ScanS10GapFill(regime string) []*Signal {
	now := config.NowIST()
	hour, min := now.Hour(), now.Minute()
	t := hour*100 + min

	// Gap fill only works in first 2 hours: 09:16 - 11:00
	if t < 916 || t > 1100 || regime == "EXTREME_PANIC" || !s.cacheReady() || !s.checkDailyTradeLimit() {
		return nil
	}

	var signals []*Signal
	for token, symbol := range s.Universe {
		current := s.GetLTP(token)
		if current <= 0 || current < 100 {
			continue
		}

		closes := s.DailyCache.Closes[token]
		if len(closes) < 5 {
			continue
		}
		prevClose := closes[len(closes)-1]
		if prevClose <= 0 {
			continue
		}

		dayOpen := 0.0
		if s.GetDayOpen != nil {
			dayOpen = s.GetDayOpen(token)
		}
		if dayOpen <= 0 {
			continue
		}

		gapPct := (dayOpen - prevClose) / prevClose * 100

		// Only trade significant gaps: 1.5% - 5% (too small = noise, too large = news-driven)
		if math.Abs(gapPct) < 1.5 || math.Abs(gapPct) > 5.0 {
			continue
		}

		rvol := s.computeRVol(token)
		if rvol < 1.0 {
			continue
		}

		atr := s.DailyCache.ATR[token]
		if atr <= 0 {
			atr = current * 0.015
		}

		// GAP UP → SHORT (fade the gap, target = prev close)
		if gapPct > 1.5 && current > prevClose*1.005 {
			// Price still above prev close, gap hasn't filled yet
			targetPrice := math.Round(prevClose*100) / 100
			stopPrice := math.Round((dayOpen+0.5*atr)*100) / 100
			risk := stopPrice - current
			if risk <= 0 {
				continue
			}

			signals = append(signals, &Signal{
				Strategy: "S10_GAP_FILL", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
				RVol: rvol, ATR: atr,
				Product: "MIS", IsShort: true, MaxHoldMins: 120,
				SortKey: math.Abs(gapPct),
			})
		}

		// GAP DOWN → LONG (fade the gap, target = prev close)
		if gapPct < -1.5 && current < prevClose*0.995 {
			targetPrice := math.Round(prevClose*100) / 100
			stopPrice := math.Round((dayOpen-0.5*atr)*100) / 100
			risk := current - stopPrice
			if risk <= 0 {
				continue
			}

			signals = append(signals, &Signal{
				Strategy: "S10_GAP_FILL", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
				RVol: rvol, ATR: atr,
				Product: "MIS", IsShort: false, MaxHoldMins: 120,
				SortKey: math.Abs(gapPct),
			})
		}
	}

	sort.Slice(signals, func(i, j int) bool { return signals[i].SortKey > signals[j].SortKey })
	if len(signals) > 3 {
		signals = signals[:3]
	}
	return signals
}

// ══════════════════════════════════════════════════════════════
//  S11: VWAP MEAN REVERSION (Pure)
//  Most used institutional intraday strategy. When price deviates
//  >2 SD from VWAP, fade toward VWAP. Unlike S6 which is a
//  band-based trend strategy, this is pure reversion.
// ══════════════════════════════════════════════════════════════
func (s *ScannerAgent) ScanS11VWAPRevert(regime string) []*Signal {
	if !s.IsInTradeWindow() || !s.checkDailyTradeLimit() || regime == "EXTREME_PANIC" || !s.cacheReady() {
		return nil
	}
	// Best after initial volatility settles: 10:00+
	now := config.NowIST()
	if now.Hour()*100+now.Minute() < 1000 {
		return nil
	}

	var signals []*Signal
	for token, symbol := range s.Universe {
		current := s.GetLTP(token)
		if current <= 0 || current < 200 {
			continue
		}

		vwap := 0.0
		if s.GetVWAP != nil {
			vwap = s.GetVWAP(token)
		}
		if vwap <= 0 {
			continue
		}

		deviation := (current - vwap) / vwap
		absDevPct := math.Abs(deviation) * 100

		// Need significant deviation: >1.5% from VWAP
		if absDevPct < 1.5 {
			continue
		}

		rvol := s.computeRVol(token)
		if rvol < 1.0 {
			continue
		}

		// Reject if volume is EXTREMELY high (news event, don't fade)
		if rvol > 5.0 {
			continue
		}

		atr := s.DailyCache.ATR[token]
		if atr <= 0 {
			atr = current * 0.015
		}

		// RSI confirmation: oversold for long, overbought for short
		candles := s.getCandles5m(token)
		if len(candles) < 14 {
			continue
		}
		closes := make([]float64, len(candles))
		for i, c := range candles {
			closes[i] = c.Close
		}
		rsiSlice := data.ComputeRSI(closes, 14)
		rsi := rsiSlice[len(rsiSlice)-1]

		// LONG: Price far below VWAP + RSI oversold
		if deviation < -0.015 && rsi < 40 {
			targetPrice := math.Round((vwap-0.002*vwap)*100) / 100 // Target slightly below VWAP
			stopPrice := math.Round((current-0.8*atr)*100) / 100
			risk := current - stopPrice
			if risk <= 0 {
				continue
			}
			potential := targetPrice - current
			if potential < 1.5*risk {
				continue // Need R:R >= 1.5
			}

			signals = append(signals, &Signal{
				Strategy: "S11_VWAP_REVERT", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
				VWAP: vwap, RVol: rvol, RSI: rsi, ATR: atr,
				Product: "MIS", IsShort: false, MaxHoldMins: 90,
				SortKey: absDevPct,
			})
		}

		// SHORT: Price far above VWAP + RSI overbought
		if deviation > 0.015 && rsi > 60 {
			targetPrice := math.Round((vwap+0.002*vwap)*100) / 100
			stopPrice := math.Round((current+0.8*atr)*100) / 100
			risk := stopPrice - current
			if risk <= 0 {
				continue
			}
			potential := current - targetPrice
			if potential < 1.5*risk {
				continue
			}

			signals = append(signals, &Signal{
				Strategy: "S11_VWAP_REVERT", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
				VWAP: vwap, RVol: rvol, RSI: rsi, ATR: atr,
				Product: "MIS", IsShort: true, MaxHoldMins: 90,
				SortKey: absDevPct,
			})
		}
	}

	sort.Slice(signals, func(i, j int) bool { return signals[i].SortKey > signals[j].SortKey })
	if len(signals) > 3 {
		signals = signals[:3]
	}
	return signals
}

// ══════════════════════════════════════════════════════════════
//  S12: END-OF-DAY MEAN REVERSION
//  Between 14:00-14:50, stocks that have moved >2% from VWAP
//  tend to revert. Institutional profit-taking creates this window.
//  Very high win rate due to forced MIS squareoff pressure.
// ══════════════════════════════════════════════════════════════
func (s *ScannerAgent) ScanS12EODReversion(regime string) []*Signal {
	now := config.NowIST()
	hour, min := now.Hour(), now.Minute()
	t := hour*100 + min

	// Only 14:00 - 14:45
	if t < 1400 || t > 1445 || regime == "EXTREME_PANIC" || !s.cacheReady() || !s.checkDailyTradeLimit() {
		return nil
	}

	var signals []*Signal
	for token, symbol := range s.Universe {
		current := s.GetLTP(token)
		if current <= 0 || current < 200 {
			continue
		}

		vwap := 0.0
		if s.GetVWAP != nil {
			vwap = s.GetVWAP(token)
		}
		if vwap <= 0 {
			continue
		}

		deviation := (current - vwap) / vwap
		absDevPct := math.Abs(deviation) * 100

		// Need >2% deviation for EOD reversion
		if absDevPct < 2.0 {
			continue
		}

		atr := s.DailyCache.ATR[token]
		if atr <= 0 {
			atr = current * 0.015
		}

		rvol := s.computeRVol(token)
		// Low volume is actually GOOD for EOD reversion (means the move is exhausted)

		// LONG: Stock beaten down >2% from VWAP in afternoon → snap back
		if deviation < -0.02 {
			targetPrice := math.Round((vwap-0.005*vwap)*100) / 100 // Partial fill toward VWAP
			stopPrice := math.Round((current-0.5*atr)*100) / 100
			risk := current - stopPrice
			if risk <= 0 {
				continue
			}

			signals = append(signals, &Signal{
				Strategy: "S12_EOD_REVERT", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
				VWAP: vwap, RVol: rvol, ATR: atr,
				Product: "MIS", IsShort: false, MaxHoldMins: 45,
				SortKey: absDevPct,
			})
		}

		// SHORT: Stock pumped >2% above VWAP → MIS squareoff will pull it down
		if deviation > 0.02 {
			targetPrice := math.Round((vwap+0.005*vwap)*100) / 100
			stopPrice := math.Round((current+0.5*atr)*100) / 100
			risk := stopPrice - current
			if risk <= 0 {
				continue
			}

			signals = append(signals, &Signal{
				Strategy: "S12_EOD_REVERT", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
				VWAP: vwap, RVol: rvol, ATR: atr,
				Product: "MIS", IsShort: true, MaxHoldMins: 45,
				SortKey: absDevPct,
			})
		}
	}

	sort.Slice(signals, func(i, j int) bool { return signals[i].SortKey > signals[j].SortKey })
	if len(signals) > 3 {
		signals = signals[:3]
	}
	return signals
}

// ══════════════════════════════════════════════════════════════
//  S13: RELATIVE STRENGTH SECTOR ROTATION
//  Buy the strongest stock in the strongest sector.
//  Short the weakest stock in the weakest sector.
//  Institutional alpha comes from sector-level momentum.
// ══════════════════════════════════════════════════════════════
func (s *ScannerAgent) ScanS13SectorRotation(regime string) []*Signal {
	if !s.IsInTradeWindow() || !s.checkDailyTradeLimit() || regime == "EXTREME_PANIC" || !s.cacheReady() {
		return nil
	}

	// Only scan every 15 minutes (not every second) — this is a slow strategy
	now := config.NowIST()
	if now.Minute()%15 != 0 {
		return nil
	}

	// Compute intraday change for each symbol
	type symbolStrength struct {
		token    uint32
		symbol   string
		changePct float64
		rvol     float64
	}

	var allStocks []symbolStrength
	for token, symbol := range s.Universe {
		current := s.GetLTP(token)
		if current <= 0 {
			continue
		}
		dayOpen := 0.0
		if s.GetDayOpen != nil {
			dayOpen = s.GetDayOpen(token)
		}
		if dayOpen <= 0 {
			continue
		}

		changePct := (current - dayOpen) / dayOpen * 100
		rvol := s.computeRVol(token)

		allStocks = append(allStocks, symbolStrength{
			token: token, symbol: symbol, changePct: changePct, rvol: rvol,
		})
	}

	if len(allStocks) < 20 {
		return nil
	}

	// Sort by change: strongest to weakest
	sort.Slice(allStocks, func(i, j int) bool { return allStocks[i].changePct > allStocks[j].changePct })

	var signals []*Signal

	// Top 3 strongest + high volume → LONG (momentum continuation)
	for i := 0; i < 3 && i < len(allStocks); i++ {
		ss := allStocks[i]
		if ss.changePct < 1.5 || ss.rvol < 1.5 {
			continue
		}

		current := s.GetLTP(ss.token)
		atr := s.DailyCache.ATR[ss.token]
		if atr <= 0 {
			atr = current * 0.015
		}
		sma200 := s.DailyCache.SMA200[ss.token]
		if sma200 > 0 && current < sma200 {
			continue // Don't buy below 200SMA
		}

		stopPrice := math.Round((current-1.0*atr)*100) / 100
		risk := current - stopPrice
		if risk <= 0 {
			continue
		}
		targetPrice := math.Round((current+2.5*risk)*100) / 100

		signals = append(signals, &Signal{
			Strategy: "S13_SECTOR_ROT", Symbol: ss.symbol, Token: ss.token, Regime: regime,
			EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
			RVol: ss.rvol, ATR: atr,
			Product: "MIS", IsShort: false,
			SortKey: ss.changePct * ss.rvol,
		})
	}

	// Bottom 3 weakest + high volume → SHORT (momentum continuation)
	for i := len(allStocks) - 1; i >= len(allStocks)-3 && i >= 0; i-- {
		ss := allStocks[i]
		if ss.changePct > -1.5 || ss.rvol < 1.5 {
			continue
		}

		current := s.GetLTP(ss.token)
		atr := s.DailyCache.ATR[ss.token]
		if atr <= 0 {
			atr = current * 0.015
		}
		sma200 := s.DailyCache.SMA200[ss.token]
		if sma200 > 0 && current > sma200 {
			continue // Don't short above 200SMA
		}

		stopPrice := math.Round((current+1.0*atr)*100) / 100
		risk := stopPrice - current
		if risk <= 0 {
			continue
		}
		targetPrice := math.Round((current-2.5*risk)*100) / 100

		signals = append(signals, &Signal{
			Strategy: "S13_SECTOR_ROT", Symbol: ss.symbol, Token: ss.token, Regime: regime,
			EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
			RVol: ss.rvol, ATR: atr,
			Product: "MIS", IsShort: true,
			SortKey: math.Abs(ss.changePct) * ss.rvol,
		})
	}

	return signals
}

// ══════════════════════════════════════════════════════════════
//  S14: RSI SCALPER (RSI-2 on 5-min — Larry Connors Method)
//  RSI(2) is the most mean-reverting indicator on short timeframes.
//  When RSI(2) < 10, price is extremely oversold → buy the bounce.
//  When RSI(2) > 90, price is extremely overbought → short the fade.
//  VWAP acts as the only trend filter. NO RVol. NO ADX.
//  This is designed to FIRE signals, not sit idle.
// ══════════════════════════════════════════════════════════════
func (s *ScannerAgent) ScanS14RSIScalp(regime string) []*Signal {
	if !s.IsInTradeWindow() || !s.checkDailyTradeLimit() || regime == "EXTREME_PANIC" || !s.cacheReady() {
		return nil
	}

	var signals []*Signal
	for token, symbol := range s.Universe {
		current := s.GetLTP(token)
		if current <= 0 || current < config.S14_MIN_PRICE {
			continue
		}

		candles := s.getCandles5m(token)
		if len(candles) < 5 {
			continue
		}
		closes := make([]float64, len(candles))
		for i, c := range candles {
			closes[i] = c.Close
		}

		// RSI(2) — ultra-short period for scalping
		rsiSlice := data.ComputeRSI(closes, config.S14_RSI_PERIOD)
		if len(rsiSlice) == 0 {
			continue
		}
		rsi2 := rsiSlice[len(rsiSlice)-1]

		// VWAP trend filter (only filter we use)
		vwap := 0.0
		if s.GetVWAP != nil {
			vwap = s.GetVWAP(token)
		}

		atr := s.DailyCache.ATR[token]
		if atr <= 0 {
			atr = current * 0.015
		}

		// LONG: RSI(2) < 10 (extreme oversold) + price above VWAP (uptrend)
		if rsi2 < float64(config.S14_RSI_OVERSOLD) && (vwap <= 0 || current > vwap) {
			stopPrice := math.Round(current*(1-config.S14_STOP_PCT)*100) / 100
			risk := current - stopPrice
			if risk <= 0 {
				continue
			}
			targetPrice := math.Round((current + 1.5*risk) * 100) / 100

			signals = append(signals, &Signal{
				Strategy: "S14_RSI_SCALP", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
				RSI: rsi2, VWAP: vwap, ATR: atr,
				Product: "MIS", IsShort: false, MaxHoldMins: config.S14_MAX_HOLD_MINS,
				SortKey: float64(config.S14_RSI_OVERSOLD) - rsi2, // Lower RSI = stronger signal
			})
		}

		// SHORT: RSI(2) > 90 (extreme overbought) + price below VWAP (downtrend)
		if rsi2 > float64(config.S14_RSI_OVERBOUGHT) && (vwap <= 0 || current < vwap) {
			stopPrice := math.Round(current*(1+config.S14_STOP_PCT)*100) / 100
			risk := stopPrice - current
			if risk <= 0 {
				continue
			}
			targetPrice := math.Round((current - 1.5*risk) * 100) / 100

			signals = append(signals, &Signal{
				Strategy: "S14_RSI_SCALP", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
				RSI: rsi2, VWAP: vwap, ATR: atr,
				Product: "MIS", IsShort: true, MaxHoldMins: config.S14_MAX_HOLD_MINS,
				SortKey: rsi2 - float64(config.S14_RSI_OVERBOUGHT), // Higher RSI = stronger signal
			})
		}
	}

	sort.Slice(signals, func(i, j int) bool { return signals[i].SortKey > signals[j].SortKey })
	if len(signals) > 5 {
		signals = signals[:5]
	}
	return signals
}

// ══════════════════════════════════════════════════════════════
//  S15: RSI SWING (RSI-14 Pullback + EMA20 Trend Confirmation)
//  Buy pullbacks in uptrends, short pullbacks in downtrends.
//  RSI(14) < 35 in an uptrend (price > EMA20) = classic dip buy.
//  RSI(14) > 65 in a downtrend (price < EMA20) = classic rally short.
//  Simple. Proven. High win rate on liquid stocks.
// ══════════════════════════════════════════════════════════════
func (s *ScannerAgent) ScanS15RSISwing(regime string) []*Signal {
	if !s.IsInTradeWindow() || !s.checkDailyTradeLimit() || regime == "EXTREME_PANIC" || !s.cacheReady() {
		return nil
	}

	var signals []*Signal
	for token, symbol := range s.Universe {
		current := s.GetLTP(token)
		if current <= 0 || current < config.S15_MIN_PRICE {
			continue
		}

		candles := s.get15MinOHLC(token)
		if len(candles) < config.S15_EMA_TREND+2 {
			continue
		}

		closes := make([]float64, len(candles))
		highs := make([]float64, len(candles))
		lows := make([]float64, len(candles))
		for i, c := range candles {
			closes[i] = c.Close
			highs[i] = c.High
			lows[i] = c.Low
		}

		// EMA20 trend filter on 15-min
		ema20 := data.ComputeEMA(closes, config.S15_EMA_TREND)
		if len(ema20) == 0 {
			continue
		}
		emaVal := ema20[len(ema20)-1]

		// RSI(14) on 15-min
		rsiSlice := data.ComputeRSI(closes, config.S15_RSI_PERIOD)
		if len(rsiSlice) == 0 {
			continue
		}
		rsi14 := rsiSlice[len(rsiSlice)-1]

		atr := s.DailyCache.ATR[token]
		if atr <= 0 {
			atr = current * 0.02
		}

		// LONG: Price > EMA20 (uptrend) + RSI < 35 (pullback/oversold)
		if current > emaVal && rsi14 < float64(config.S15_RSI_OVERSOLD) {
			stopPrice := math.Round((current - config.S15_ATR_SL_MULT*atr) * 100) / 100
			risk := current - stopPrice
			if risk <= 0 {
				continue
			}
			targetPrice := math.Round((current + config.S15_RR*risk) * 100) / 100

			signals = append(signals, &Signal{
				Strategy: "S15_RSI_SWING", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice,
				PartialTarget: math.Round((current + 1.0*risk) * 100) / 100,
				TargetPrice: targetPrice, RSI: rsi14, ATR: atr,
				Product: "MIS", IsShort: false, MaxHoldMins: config.S15_MAX_HOLD_MINS,
				SortKey: float64(config.S15_RSI_OVERSOLD) - rsi14,
			})
		}

		// SHORT: Price < EMA20 (downtrend) + RSI > 65 (rally/overbought)
		if current < emaVal && rsi14 > float64(config.S15_RSI_OVERBOUGHT) {
			stopPrice := math.Round((current + config.S15_ATR_SL_MULT*atr) * 100) / 100
			risk := stopPrice - current
			if risk <= 0 {
				continue
			}
			targetPrice := math.Round((current - config.S15_RR*risk) * 100) / 100

			signals = append(signals, &Signal{
				Strategy: "S15_RSI_SWING", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice,
				PartialTarget: math.Round((current - 1.0*risk) * 100) / 100,
				TargetPrice: targetPrice, RSI: rsi14, ATR: atr,
				Product: "MIS", IsShort: true, MaxHoldMins: config.S15_MAX_HOLD_MINS,
				SortKey: rsi14 - float64(config.S15_RSI_OVERBOUGHT),
			})
		}
	}

	sort.Slice(signals, func(i, j int) bool { return signals[i].SortKey > signals[j].SortKey })
	if len(signals) > 5 {
		signals = signals[:5]
	}
	return signals
}

// RunAllScans executes all strategies and returns combined signals
// FILTERED by net profitability — no signal reaches execution unless it
// can produce ≥₹15 net profit after ALL Zerodha charges.
func (s *ScannerAgent) RunAllScans(regime string) []*Signal {
	var all []*Signal

	s1 := s.ScanS1(regime)
	s2 := s.ScanS2(regime)
	s3 := s.ScanS3(regime)
	s6t := s.ScanS6TrendShort(regime)
	s6v := s.ScanS6VWAP(regime)
	s7 := s.ScanS7(regime)
	s8 := s.ScanS8(regime)
	s9 := s.ScanS9(regime)
	s10 := s.ScanS10GapFill(regime)
	s11 := s.ScanS11VWAPRevert(regime)
	s12 := s.ScanS12EODReversion(regime)
	s13 := s.ScanS13SectorRotation(regime)
	s14 := s.ScanS14RSIScalp(regime)
	s15 := s.ScanS15RSISwing(regime)

	all = append(all, s1...)
	all = append(all, s2...)
	all = append(all, s3...)
	all = append(all, s6t...)
	all = append(all, s6v...)
	all = append(all, s7...)
	all = append(all, s8...)
	all = append(all, s9...)
	all = append(all, s10...)
	all = append(all, s11...)
	all = append(all, s12...)
	all = append(all, s13...)
	all = append(all, s14...)
	all = append(all, s15...)

	// Catch-all to populate missing ML prerequisites for ANY strategy
	for _, sig := range all {
		if sig.RSI == 0 || sig.ADX == 0 || sig.RVol == 0 {
			if sig.RVol == 0 && s.ComputeRVol != nil {
				sig.RVol = s.ComputeRVol(sig.Token)
			}
			
			candles := s.getCandles5m(sig.Token)
			if len(candles) >= 15 {
				closes := make([]float64, len(candles))
				highs := make([]float64, len(candles))
				lows := make([]float64, len(candles))
				for i, c := range candles {
					closes[i] = c.Close
					highs[i] = c.High
					lows[i] = c.Low
				}
				
				if sig.RSI == 0 {
					rsiSlice := data.ComputeRSI(closes, 14)
					sig.RSI = rsiSlice[len(rsiSlice)-1]
				}
				if sig.ADX == 0 {
					sig.ADX = data.ComputeADX(highs, lows, closes, 14)
				}
			} else if sig.RSI == 0 {
				sig.RSI = 50.0 // Neutral fallback if data is missing
			}
		}
	}

	// ═══ ALWAYS-ON DIAGNOSTICS (every 30s) ═══
	// Shows exactly WHY signals aren't generating — never go silent
	now := config.NowIST()
	if now.Second() == 0 || now.Second() == 30 {
		// Count stocks with valid LTP
		ltpCount := 0
		candleCount := 0
		for token := range s.Universe {
			if s.GetLTP != nil && s.GetLTP(token) > 0 {
				ltpCount++
			}
			if c := s.getCandles5m(token); len(c) >= 2 {
				candleCount++
			}
		}
		log.Printf("[DIAG] Universe=%d LTP_active=%d Candles5m≥2=%d CacheReady=%v InWindow=%v Regime=%s",
			len(s.Universe), ltpCount, candleCount, s.cacheReady(), s.IsInTradeWindow(), regime)
		log.Printf("[DIAG] RAW: S1=%d S2=%d S3=%d S6T=%d S6V=%d S7=%d S8=%d S9=%d S10=%d S11=%d S12=%d S13=%d S14=%d S15=%d TOTAL=%d",
			len(s1), len(s2), len(s3), len(s6t), len(s6v), len(s7), len(s8), len(s9), len(s10), len(s11), len(s12), len(s13), len(s14), len(s15), len(all))
	}

	// CRITICAL: Filter by net profitability — remove any signal that can't cover charges
	filtered := s.FilterByNetProfit(all, config.TotalCapital)

	if len(all) > 0 && len(filtered) < len(all) {
		log.Printf("[Scanner] Charge filter: %d/%d signals passed (rejected %d unprofitable)",
			len(filtered), len(all), len(all)-len(filtered))
	}

	return filtered
}
