package agents

import (
	"log"
	"math"
	"sort"
	"time"

	"bnf_go_engine/config"
	"bnf_go_engine/core"
	"bnf_go_engine/data"
)

// Signal represents a trade signal generated by a strategy scan
type Signal struct {
	Strategy        string
	Symbol          string
	Token           uint32
	Regime          string
	EntryPrice      float64
	StopPrice       float64
	PartialTarget   float64
	TargetPrice     float64
	ATR             float64
	ADX             float64
	RVol            float64
	RSI             float64
	VWAP            float64
	Product         string
	IsShort         bool
	MaxHoldMins     int
	SortKey         float64
	ExpectedNetPnL  float64 // Expected net profit after charges at target
	EstCharges      float64 // Estimated round-trip charges
	Qty             int     // Pre-computed quantity from position sizing
}

// ScannerAgent — exact port of Python scanner_agent.py
type ScannerAgent struct {
	// Data references (will be set by engine)
	Universe       map[uint32]string // token -> symbol
	TokenToCompany map[uint32]string // token -> company name
	GetLTP         func(uint32) float64
	GetVWAP        func(uint32) float64
	GetVolume      func(uint32) int64
	GetDepth       func(uint32) map[string]float64
	GetCandles5m   func(uint32) []Candle
	GetORB         func(uint32) (float64, float64) // high, low
	DailyCache     *DailyCache
	ComputeRVol  func(uint32) float64
	GetIntraday  func(uint32, string) []Candle
	GetIndiaVIX  func() float64
	GetADRatio   func() float64
	GetDayOpen   func(uint32) float64
	SimulatorMode bool // When true, bypasses time/cooldown checks for backtesting

	// Cooldown tracking
	s6Cooldown       map[string]time.Time
	s3TradesToday    int
	s3TradeDate      time.Time
	s6vTradesToday   int
	s6vTradeDate     time.Time
	s6vLastLossTime  time.Time
	symbolCooldown   map[string]int
	dailyPnl         float64
	dailyPnlDate     time.Time
	LastRegime       string // Shared regime for both main loop and API

	// Per-strategy adaptive kill switch: if a strategy loses N times today, disable it
	strategyLossesToday map[string]int

	// S13 per-symbol signal cooldown: prevents re-signaling same stock every 15 minutes
	s13SignalCooldown map[string]time.Time

	// Regime stability: count consecutive confirmations before switching
	regimeConfirmCount int
}

// Candle represents OHLCV data
type Candle struct {
	Open   float64
	High   float64
	Low    float64
	Close  float64
	Volume int64
}

// DailyCache mocks the precomputed daily cache
type DailyCache struct {
	SMA200  map[uint32]float64
	ATR     map[uint32]float64
	EMA25   map[uint32]float64
	BBLower map[uint32]float64
	Closes  map[uint32][]float64
	Highs   map[uint32][]float64
	Lows    map[uint32][]float64
	AvgVol  map[uint32]float64
	TurnoverCr map[uint32]float64
	PivotSupport map[uint32]float64
	Loaded  bool
}

func NewScannerAgent() *ScannerAgent {
	return &ScannerAgent{
		s6Cooldown:          make(map[string]time.Time),
		symbolCooldown:      make(map[string]int),
		strategyLossesToday: make(map[string]int),
		s13SignalCooldown:   make(map[string]time.Time),
	}
}

// ── Regime Detection (VIX + AD Ratio of 250-stock universe) ──
// No Nifty 50 dependency. AD ratio of our universe IS the broad market direction.
// 3 states only: BULLISH / BEARISH / SIDEWAYS
// Regime stability: requires 2 consecutive confirmations before switching (prevents flipping)
func (s *ScannerAgent) DetectRegime() string {
	vix := 16.0
	if s.GetIndiaVIX != nil {
		v := s.GetIndiaVIX()
		if v > 0 {
			vix = v
		}
	}

	adRatio := 0.5
	if s.GetADRatio != nil {
		a := s.GetADRatio()
		if a > 0 {
			adRatio = a
		}
	}

	// ═══ SIMPLE 3-STATE MODEL ═══
	// VIX < 20 + majority stocks up = BULLISH
	// VIX > 20 + majority stocks down = BEARISH
	// Everything else = SIDEWAYS (most common — run all strategies)
	candidate := "SIDEWAYS"
	if vix >= 30 {
		// Extreme VIX = always BEARISH regardless of AD ratio
		candidate = "BEARISH"
	} else if vix < 20 && adRatio > 0.55 {
		candidate = "BULLISH"
	} else if vix > 20 && adRatio < 0.45 {
		candidate = "BEARISH"
	}

	// ═══ REGIME STABILITY ═══
	// Only change regime after 2 consecutive confirmations of the NEW state.
	// This prevents the CHOP↔NORMAL flipping (10 changes on May 6).
	if candidate != s.LastRegime {
		s.regimeConfirmCount++
		if s.regimeConfirmCount >= 2 {
			// Confirmed — switch regime
			log.Printf("[Regime] %s → %s (VIX=%.1f AD=%.2f) — confirmed after %d checks",
				s.LastRegime, candidate, vix, adRatio, s.regimeConfirmCount)
			s.LastRegime = candidate
			s.regimeConfirmCount = 0
		} else {
			log.Printf("[Regime] Candidate=%s (VIX=%.1f AD=%.2f) — need %d more confirmation(s), staying %s",
				candidate, vix, adRatio, 2-s.regimeConfirmCount, s.LastRegime)
		}
	} else {
		s.regimeConfirmCount = 0 // Reset counter when candidate matches current
	}

	// First-time initialization
	if s.LastRegime == "" || s.LastRegime == "UNKNOWN" {
		s.LastRegime = candidate
	}

	return s.LastRegime
}

// ── Time Enforcement ─────────────────────────────────────────
func (s *ScannerAgent) IsInTradeWindow() bool {
	if s.SimulatorMode {
		return true
	}
	now := config.NowIST()
	t := now.Hour()*100 + now.Minute()
	sh, sm := config.ParseTime(config.TradeWindowStart)
	eh, em := config.ParseTime(config.TradeWindowEnd)
	start := sh*100 + sm
	end := eh*100 + em
	return t >= start && t <= end
}

func (s *ScannerAgent) checkDailyTradeLimit() bool {
	if s.SimulatorMode {
		return true // No daily trade limits in backtest
	}
	if s.CircuitBreakerTripped() {
		return false
	}
	return true
}

func (s *ScannerAgent) CircuitBreakerTripped() bool {
	return s.dailyPnl < -(config.TotalCapital * config.DailyLossLimitPct)
}

func (s *ScannerAgent) RecordPnl(pnl float64) {
	s.dailyPnl += pnl
}

func (s *ScannerAgent) NewSession() {
	s.dailyPnl = 0
	s.s6vTradesToday = 0
	s.s6vLastLossTime = time.Time{}
	s.strategyLossesToday = make(map[string]int) // Reset daily kill switch
	s.s13SignalCooldown = make(map[string]time.Time) // Reset S13 per-symbol cooldown

	expired := []string{}
	for k, v := range s.symbolCooldown {
		if v <= 1 {
			expired = append(expired, k)
		}
	}
	for _, k := range expired {
		delete(s.symbolCooldown, k)
	}
	for k := range s.symbolCooldown {
		s.symbolCooldown[k]--
	}
}

// ── Per-Strategy Adaptive Kill Switch ────────────────────────
const StrategyDailyLossLimit = 3 // 3 losses today → strategy paused for the day

// RecordStrategyResult tracks wins/losses per strategy for adaptive disabling
func (s *ScannerAgent) RecordStrategyResult(strategy string, pnl float64) {
	if pnl < 0 {
		s.strategyLossesToday[strategy]++
		if s.strategyLossesToday[strategy] >= StrategyDailyLossLimit {
			log.Printf("[Scanner] STRATEGY KILL: %s disabled after %d losses today",
				strategy, s.strategyLossesToday[strategy])
		}
	} else if pnl > 0 {
		// A win resets the loss counter (strategy is working)
		s.strategyLossesToday[strategy] = 0
	}
}

// IsStrategyKilledToday returns true if a strategy has hit its daily loss limit
func (s *ScannerAgent) IsStrategyKilledToday(strategy string) bool {
	return s.strategyLossesToday[strategy] >= StrategyDailyLossLimit
}

func (s *ScannerAgent) cacheReady() bool {
	return s.DailyCache != nil && s.DailyCache.Loaded && s.GetLTP != nil
}

// GetCurrentVIX returns current India VIX value for ML filter
func (s *ScannerAgent) GetCurrentVIX() float64 {
	if s.GetIndiaVIX != nil {
		return s.GetIndiaVIX()
	}
	return 16.0
}

// GetCurrentADRatio returns current advance-decline ratio for ML filter
func (s *ScannerAgent) GetCurrentADRatio() float64 {
	if s.GetADRatio != nil {
		return s.GetADRatio()
	}
	return 0.5
}

// ── Helpers ──────────────────────────────────────────────────
func (s *ScannerAgent) get15MinCloses(token uint32) []float64 {
	candles := s.getCandles5m(token)
	if len(candles) < 3 {
		return nil
	}
	var closes []float64
	for i := 2; i < len(candles); i += 3 {
		closes = append(closes, candles[i].Close)
	}
	return closes
}

func (s *ScannerAgent) get15MinOHLC(token uint32) []Candle {
	candles := s.getCandles5m(token)
	var bars []Candle
	for i := 0; i+2 < len(candles); i += 3 {
		group := candles[i : i+3]
		h := group[0].High
		l := group[0].Low
		var vol int64
		for _, c := range group {
			if c.High > h { h = c.High }
			if c.Low < l { l = c.Low }
			vol += c.Volume
		}
		bars = append(bars, Candle{
			Open: group[0].Open, High: h, Low: l, Close: group[2].Close, Volume: vol,
		})
	}
	return bars
}

func (s *ScannerAgent) getCandles5m(token uint32) []Candle {
	if s.GetCandles5m != nil {
		return s.GetCandles5m(token)
	}
	return nil
}

func (s *ScannerAgent) checkOrderBook(token uint32, isShort bool) bool {
	if s.GetDepth == nil {
		return true
	}
	depth := s.GetDepth(token)
	if depth == nil {
		return true
	}
	ratio := depth["bid_ask_ratio"]
	if isShort && ratio > 2.0 {
		return false
	}
	if !isShort && ratio < 0.5 {
		return false
	}
	return true
}

// ══════════════════════════════════════════════════════════════
//  S1: MA CROSSOVER
// ══════════════════════════════════════════════════════════════
func (s *ScannerAgent) ScanS1(regime string) []*Signal {
	if !s.IsInTradeWindow() || !s.checkDailyTradeLimit() || regime == "EXTREME_PANIC" || !s.cacheReady() {
		return nil
	}

	var signals []*Signal
	for token, symbol := range s.Universe {
		current := s.GetLTP(token)
		if current <= 0 {
			continue
		}

		// SMA200 filter REMOVED — S1 now fires on EMA crossovers regardless of long-term trend

		c15 := s.get15MinCloses(token)
		if len(c15) < config.S1_EMA_SLOW+2 {
			continue
		}

		ema9 := data.ComputeEMA(c15, config.S1_EMA_FAST)
		ema21 := data.ComputeEMA(c15, config.S1_EMA_SLOW)
		if len(ema9) < 2 || len(ema21) < 2 {
			continue
		}

		ema9Now, ema9Prev := ema9[len(ema9)-1], ema9[len(ema9)-2]
		ema21Now, ema21Prev := ema21[len(ema21)-1], ema21[len(ema21)-2]

		crossUp := ema9Prev <= ema21Prev && ema9Now > ema21Now
		crossDown := ema9Prev >= ema21Prev && ema9Now < ema21Now

		if !crossUp && !crossDown {
			continue
		}

		rvol := s.computeRVol(token)
		if rvol < 0.8 {
			continue
		}

		candles := s.get15MinOHLC(token)
		if len(candles) < config.S1_ADX_PERIOD+2 {
			continue
		}

		highs := make([]float64, len(candles))
		lows := make([]float64, len(candles))
		closes := make([]float64, len(candles))
		for i, c := range candles {
			highs[i] = c.High
			lows[i] = c.Low
			closes[i] = c.Close
		}

		adx := data.ComputeADX(highs, lows, closes, config.S1_ADX_PERIOD)
		if adx < float64(config.S1_ADX_MIN) {
			continue
		}

		// ATR
		var atrVals []float64
		for i := 1; i < len(highs); i++ {
			tr := math.Max(highs[i]-lows[i], math.Max(math.Abs(highs[i]-closes[i-1]), math.Abs(lows[i]-closes[i-1])))
			atrVals = append(atrVals, tr)
		}
		atr := current * 0.015
		if len(atrVals) >= 14 {
			sum := 0.0
			for _, v := range atrVals[len(atrVals)-14:] {
				sum += v
			}
			atr = sum / 14.0
		}

		// EMA21 slope check REMOVED — redundant with cross direction

		// MACD confirmation REMOVED — was too restrictive, S1 never fired
		// EMA crossover is already a trend signal; MACD adds redundant lag

		if crossUp {
			stopPrice := math.Round((current-config.S1_ATR_SL_MULT*atr)*100) / 100
			risk := current - stopPrice
			if risk <= 0 {
				continue
			}
			targetPrice := math.Round((current+config.S1_RR*risk)*100) / 100
			signals = append(signals, &Signal{
				Strategy: "S1_MA_CROSS", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice,
				PartialTarget: math.Round((current+1.0*risk)*100) / 100,
				TargetPrice: targetPrice, ATR: atr, ADX: adx, RVol: rvol,
				Product: "MIS", IsShort: false, SortKey: adx,
			})
		} else if crossDown {
			stopPrice := math.Round((current+config.S1_ATR_SL_MULT*atr)*100) / 100
			risk := stopPrice - current
			if risk <= 0 {
				continue
			}
			targetPrice := math.Round((current-config.S1_RR*risk)*100) / 100
			signals = append(signals, &Signal{
				Strategy: "S1_MA_CROSS", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice,
				PartialTarget: math.Round((current-1.0*risk)*100) / 100,
				TargetPrice: targetPrice, ATR: atr, ADX: adx, RVol: rvol,
				Product: "MIS", IsShort: true, SortKey: adx,
			})
		}
	}

	sort.Slice(signals, func(i, j int) bool { return signals[i].SortKey > signals[j].SortKey })
	if len(signals) > 3 {
		signals = signals[:3]
	}
	return signals
}

// ══════════════════════════════════════════════════════════════
//  S2: BB + RSI MEAN REVERSION
// ══════════════════════════════════════════════════════════════
func (s *ScannerAgent) ScanS2(regime string) []*Signal {
	if !s.IsInTradeWindow() || !s.checkDailyTradeLimit() || regime == "EXTREME_PANIC" || !s.cacheReady() {
		return nil
	}
	vix := 16.0
	if s.GetIndiaVIX != nil {
		vix = s.GetIndiaVIX()
	}
	if vix > config.S2_VIX_MAX {
		return nil
	}

	var signals []*Signal
	for token, symbol := range s.Universe {
		current := s.GetLTP(token)
		if current <= 0 {
			continue
		}

		candles := s.getCandles5m(token)
		if len(candles) < config.S2_BB_PERIOD {
			continue
		}
		closes := make([]float64, len(candles))
		for i, c := range candles {
			closes[i] = c.Close
		}

		bbHi, bbMid, bbLo := data.ComputeBollinger(closes, config.S2_BB_PERIOD, config.S2_BB_SD)
		rsiSlice := data.ComputeRSI(closes, config.S2_RSI_PERIOD)
		rsiVal := rsiSlice[len(rsiSlice)-1]

		vwap := 0.0
		if s.GetVWAP != nil {
			vwap = s.GetVWAP(token)
		}
		if vwap <= 0 {
			continue
		}
		// vwapDev filter REMOVED — was too restrictive, prevented S2 from ever firing

		atr := s.DailyCache.ATR[token]
		if atr <= 0 {
			atr = current * 0.015
		}

		rvol := s.computeRVol(token)
		if rvol < 0.8 {
			continue
		}

		if len(candles) < 2 {
			continue
		}
		prevCandle := candles[len(candles)-2]
		currCandle := candles[len(candles)-1]

		// SMA200 filter REMOVED for longs — mean reversion works at any price level

		// LONG
		// LONG: BB lower touch + RSI confirmation (removed vwapDev + SMA200 filters — too restrictive)
		if prevCandle.Close < bbLo && currCandle.Close > bbLo && rsiVal < float64(config.S2_RSI_OVERSOLD) {
			stopPrice := math.Round((current-config.S2_ATR_SL_MULT*atr)*100) / 100
			targetPrice := math.Round(bbMid*100) / 100
			risk := current - stopPrice
			if targetPrice <= current*1.001 {
				targetPrice = math.Round((current+config.S2_RR*(current-stopPrice))*100) / 100
			}
			signals = append(signals, &Signal{
				Strategy: "S2_BB_MEAN_REV", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice,
				PartialTarget: math.Round((current+1.0*risk)*100) / 100,
				TargetPrice: targetPrice, RSI: rsiVal, VWAP: vwap, ATR: atr,
				Product: "MIS", IsShort: false, MaxHoldMins: config.S2_MAX_HOLD_MINS,
				SortKey: math.Abs(rsiVal - 50),
			})
		}

		// SHORT
		// SHORT: BB upper touch + RSI confirmation (removed vwapDev filter)
		if prevCandle.Close > bbHi && currCandle.Close < bbHi && rsiVal > float64(config.S2_RSI_OVERBOUGHT) {
			stopPrice := math.Round((current+config.S2_ATR_SL_MULT*atr)*100) / 100
			targetPrice := math.Round(bbMid*100) / 100
			risk := stopPrice - current
			if targetPrice >= current*0.999 {
				targetPrice = math.Round((current-config.S2_RR*(stopPrice-current))*100) / 100
			}
			signals = append(signals, &Signal{
				Strategy: "S2_BB_MEAN_REV", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice,
				PartialTarget: math.Round((current-1.0*risk)*100) / 100,
				TargetPrice: targetPrice, RSI: rsiVal, VWAP: vwap, ATR: atr,
				Product: "MIS", IsShort: true, MaxHoldMins: config.S2_MAX_HOLD_MINS,
				SortKey: math.Abs(rsiVal - 50),
			})
		}
	}

	sort.Slice(signals, func(i, j int) bool { return signals[i].SortKey > signals[j].SortKey })
	if len(signals) > 3 {
		signals = signals[:3]
	}
	return signals
}

// ══════════════════════════════════════════════════════════════
//  S3: OPENING RANGE BREAKOUT
// ══════════════════════════════════════════════════════════════
func (s *ScannerAgent) ScanS3(regime string) []*Signal {
	if !s.IsInTradeWindow() || regime == "EXTREME_PANIC" || !s.checkDailyTradeLimit() || !s.cacheReady() {
		return nil
	}

	today := config.TodayIST()
	if !s.s3TradeDate.Equal(today) {
		s.s3TradesToday = 0
		s.s3TradeDate = today
	}
	if s.s3TradesToday >= 5 {
		return nil
	}

	var signals []*Signal
	for token, symbol := range s.Universe {
		current := s.GetLTP(token)
		if current <= 0 || current < 800 {
			continue
		}

		rvol := s.computeRVol(token)
		if rvol < 1.0 {
			continue
		}

		orbHigh, orbLow := 0.0, 0.0
		if s.GetORB != nil {
			orbHigh, orbLow = s.GetORB(token)
		}
		if orbHigh <= 0 || orbLow <= 0 {
			continue
		}

		atr := s.DailyCache.ATR[token]
		if atr <= 0 {
			atr = current * 0.015
		}

		// Volume confirmation: breakout candle must have above-average volume
		candles := s.getCandles5m(token)
		if len(candles) >= 4 {
			currVol := candles[len(candles)-1].Volume
			var avgVol int64
			for _, c := range candles[:len(candles)-1] {
				avgVol += c.Volume
			}
			avgVol /= int64(len(candles) - 1)
			if avgVol > 0 && currVol < int64(float64(avgVol)*1.5) {
				continue // Breakout on thin volume = likely fakeout
			}
		}

		// LONG
		if current > orbHigh+atr*0.3 {
			if !s.checkOrderBook(token, false) {
				continue
			}
			stopPrice := math.Round((orbLow-atr*0.2)*100) / 100
			risk := current - stopPrice
			if risk <= 0 {
				continue
			}
			targetPrice := math.Round((current+2.5*risk)*100) / 100
			signals = append(signals, &Signal{
				Strategy: "S3_ORB", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
				RVol: rvol, Product: "MIS", IsShort: false, SortKey: rvol,
			})
		}

		// SHORT
		if current < orbLow-atr*0.3 {
			if !s.checkOrderBook(token, true) {
				continue
			}
			stopPrice := math.Round((orbHigh+atr*0.2)*100) / 100
			risk := stopPrice - current
			if risk <= 0 {
				continue
			}
			targetPrice := math.Round((current-2.5*risk)*100) / 100
			signals = append(signals, &Signal{
				Strategy: "S3_ORB", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
				RVol: rvol, Product: "MIS", IsShort: true, SortKey: rvol,
			})
		}
	}

	// NOTE: s3TradesToday is incremented in Execute(), not here.
	// Counting on generation causes rejected signals to consume the daily limit.

	sort.Slice(signals, func(i, j int) bool { return signals[i].SortKey > signals[j].SortKey })
	if len(signals) > 1 {
		signals = signals[:1]
	}
	return signals
}

// ══════════════════════════════════════════════════════════════
//  S6 VWAP BAND
// ══════════════════════════════════════════════════════════════
func (s *ScannerAgent) ScanS6VWAP(regime string) []*Signal {
	if !s.IsInTradeWindow() || !s.checkDailyTradeLimit() || regime == "EXTREME_PANIC" || !s.cacheReady() {
		return nil
	}

	var signals []*Signal
	for token, symbol := range s.Universe {
		current := s.GetLTP(token)
		if current <= 0 || current < 400 {
			continue
		}

		turnover := s.DailyCache.TurnoverCr[token]
		if turnover < 40 {
			continue
		}

		vwap := 0.0
		if s.GetVWAP != nil {
			vwap = s.GetVWAP(token)
		}
		if vwap <= 0 {
			continue
		}

		candles := s.getCandles5m(token)
		if len(candles) < 20 {
			continue
		}
		closes := make([]float64, len(candles))
		for i, c := range candles {
			closes[i] = c.Close
		}

		_, _, vwapSD := data.ComputeBollinger(closes[len(closes)-20:], 20, config.S6_VWAP_SD)
		if vwapSD <= 0 {
			vwapSD = current * 0.008
		}

		rvol := s.computeRVol(token)
		if rvol < 0.8 {
			continue
		}

		rsiSlice := data.ComputeRSI(closes, 14)
		rsi := rsiSlice[len(rsiSlice)-1]

		// LONG
		if current < vwap-1.8*vwapSD && rsi < 35 {
			stopPrice := math.Round((current-1.2*vwapSD)*100) / 100
			risk := current - stopPrice
			if risk <= 0 {
				continue
			}
			targetPrice := math.Round(vwap*100) / 100
			if (targetPrice - current) < 2.0*risk {
				targetPrice = math.Round((current+2.0*risk)*100) / 100
			}
			signals = append(signals, &Signal{
				Strategy: "S6_VWAP_BAND", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
				VWAP: vwap, RVol: rvol, RSI: rsi,
				Product: "MIS", IsShort: false,
				SortKey: math.Abs(current - vwap),
			})
		}

		// SHORT
		if current > vwap+1.8*vwapSD && rsi > 65 {
			stopPrice := math.Round((current+1.2*vwapSD)*100) / 100
			risk := stopPrice - current
			if risk <= 0 {
				continue
			}
			targetPrice := math.Round(vwap*100) / 100
			if (current - targetPrice) < 2.0*risk {
				targetPrice = math.Round((current-2.0*risk)*100) / 100
			}
			signals = append(signals, &Signal{
				Strategy: "S6_VWAP_BAND", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
				VWAP: vwap, RVol: rvol, RSI: rsi,
				Product: "MIS", IsShort: true,
				SortKey: math.Abs(current - vwap),
			})
		}
	}

	sort.Slice(signals, func(i, j int) bool { return signals[i].SortKey > signals[j].SortKey })
	if len(signals) > 2 {
		signals = signals[:2]
	}
	return signals
}

// ══════════════════════════════════════════════════════════════
//  S8: VOLUME PROFILE + PIVOT
// ══════════════════════════════════════════════════════════════
func (s *ScannerAgent) ScanS8(regime string) []*Signal {
	if !s.IsInTradeWindow() || !s.checkDailyTradeLimit() || regime == "EXTREME_PANIC" || !s.cacheReady() {
		return nil
	}

	var signals []*Signal
	for token, symbol := range s.Universe {
		current := s.GetLTP(token)
		if current <= 0 || current < 300 {
			continue
		}

		closes := s.DailyCache.Closes[token]
		highs := s.DailyCache.Highs[token]
		lows := s.DailyCache.Lows[token]
		if len(closes) < 2 || len(highs) < 2 || len(lows) < 2 {
			continue
		}

		// DailyCache.Closes last element = yesterday's close (Kite returns completed bars only)
		// So -1 = yesterday, -2 = day before yesterday
		prevH := highs[len(highs)-1]
		prevL := lows[len(lows)-1]
		prevC := closes[len(closes)-1]
		pivot := (prevH + prevL + prevC) / 3
		r1 := 2*pivot - prevL
		s1 := 2*pivot - prevH
		r2 := pivot + (prevH - prevL)
		s2 := pivot - (prevH - prevL)

		rvol := s.computeRVol(token)
		if rvol < 1.2 {
			continue
		}

		atr := s.DailyCache.ATR[token]
		if atr <= 0 {
			atr = current * 0.015
		}

		candles := s.getCandles5m(token)
		if len(candles) < 2 {
			continue
		}
		currCandle := candles[len(candles)-1]
		prevCandle := candles[len(candles)-2]

		// LONG
		r1Breakout := currCandle.Close > r1
		r1Retest := prevCandle.Close > r1 && currCandle.Low <= r1 && currCandle.Close > r1
		if r1Breakout || r1Retest {
			stopPrice := math.Round((r1-0.15*atr)*100) / 100
			risk := current - stopPrice
			if risk <= 0 {
				stopPrice = math.Round((current-0.5*atr)*100) / 100
				risk = current - stopPrice
			}
			if risk <= 0 {
				continue
			}
			targetPrice := math.Round(r2*100) / 100
			if targetPrice <= current || r2 <= r1 {
				continue
			}
			targetPrice = math.Max(targetPrice, math.Round((current+1.5*risk)*100)/100)

			signals = append(signals, &Signal{
				Strategy: "S8_VOL_PIVOT", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice,
				PartialTarget: math.Round((current+1.0*risk)*100) / 100,
				TargetPrice: targetPrice, RVol: rvol, ATR: atr,
				Product: "MIS", IsShort: false, SortKey: rvol,
			})
		} else {
			// SHORT
			s1Breakdown := currCandle.Close < s1
			s1Retest := prevCandle.Close < s1 && currCandle.High >= s1 && currCandle.Close < s1
			if s1Breakdown || s1Retest {
				stopPrice := math.Round((s1+0.15*atr)*100) / 100
				risk := stopPrice - current
				if risk <= 0 {
					stopPrice = math.Round((current+0.5*atr)*100) / 100
					risk = stopPrice - current
				}
				if risk <= 0 {
					continue
				}
				targetPrice := math.Round(s2*100) / 100
				if targetPrice >= current || s2 <= 0 {
					continue
				}
				targetPrice = math.Min(targetPrice, math.Round((current-1.5*risk)*100)/100)

				signals = append(signals, &Signal{
					Strategy: "S8_VOL_PIVOT", Symbol: symbol, Token: token, Regime: regime,
					EntryPrice: current, StopPrice: stopPrice,
					PartialTarget: math.Round((current-1.0*risk)*100) / 100,
					TargetPrice: targetPrice, RVol: rvol, ATR: atr,
					Product: "MIS", IsShort: true, SortKey: rvol,
				})
			}
		}
	}

	sort.Slice(signals, func(i, j int) bool { return signals[i].SortKey > signals[j].SortKey })
	if len(signals) > 3 {
		signals = signals[:3]
	}
	return signals
}

// ══════════════════════════════════════════════════════════════
//  S9: MULTI-TIMEFRAME MOMENTUM
// ══════════════════════════════════════════════════════════════
func (s *ScannerAgent) ScanS9(regime string) []*Signal {
	if !s.IsInTradeWindow() || regime == "EXTREME_PANIC" || !s.checkDailyTradeLimit() || !s.cacheReady() {
		return nil
	}

	var signals []*Signal
	for token, symbol := range s.Universe {
		current := s.GetLTP(token)
		if current <= 0 || current < 300 {
			continue
		}

		closesD := s.DailyCache.Closes[token]
		if len(closesD) < config.S9_EMA_TREND+5 {
			continue
		}
		ema200Daily := data.ComputeEMA(closesD, config.S9_EMA_TREND)
		isUptrend := current > ema200Daily[len(ema200Daily)-1]

		candles := s.getCandles5m(token)
		if len(candles) < 30 {
			continue
		}
		cCloses := make([]float64, len(candles))
		for i, c := range candles {
			cCloses[i] = c.Close
		}

		macdVal, signalVal, _ := data.ComputeMACD(cCloses, 12, 26, 9)
		macdPrev, signalPrev, _ := data.ComputeMACD(cCloses[:len(cCloses)-1], 12, 26, 9)

		rsiSlice := data.ComputeRSI(cCloses, config.S9_RSI_PERIOD)
		rsi15 := rsiSlice[len(rsiSlice)-1]

		rvol := s.computeRVol(token)
		if regime == "CHOP" && rvol < 1.3 {
			continue
		}
		if rvol < 1.0 {
			continue
		}

		atr := s.DailyCache.ATR[token]
		if atr <= 0 {
			atr = current * 0.02
		}

		// LONG
		if isUptrend && rsi15 > float64(config.S9_RSI_THRESHOLD) && macdPrev < signalPrev && macdVal > signalVal {
			stopPrice := math.Round((current-config.S9_ATR_SL_MULT*atr)*100) / 100
			risk := current - stopPrice
			if risk <= 0 {
				continue
			}
			targetPrice := math.Round((current+config.S9_RR*risk)*100) / 100
			signals = append(signals, &Signal{
				Strategy: "S9_MTF_MOMENTUM", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice,
				PartialTarget: math.Round((current+1.0*risk)*100) / 100,
				TargetPrice: targetPrice, RVol: rvol, ATR: atr, RSI: rsi15,
				Product: "MIS", IsShort: false, SortKey: math.Abs(rsi15 - 50),
			})
		}

		// SHORT
		if !isUptrend && rsi15 < float64(100-config.S9_RSI_THRESHOLD) && macdPrev > signalPrev && macdVal < signalVal {
			stopPrice := math.Round((current+config.S9_ATR_SL_MULT*atr)*100) / 100
			risk := stopPrice - current
			if risk <= 0 {
				continue
			}
			targetPrice := math.Round((current-config.S9_RR*risk)*100) / 100
			signals = append(signals, &Signal{
				Strategy: "S9_MTF_MOMENTUM", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice,
				PartialTarget: math.Round((current-1.0*risk)*100) / 100,
				TargetPrice: targetPrice, RVol: rvol, ATR: atr, RSI: rsi15,
				Product: "MIS", IsShort: true, SortKey: math.Abs(rsi15 - 50),
			})
		}
	}

	sort.Slice(signals, func(i, j int) bool { return signals[i].SortKey > signals[j].SortKey })
	if len(signals) > 3 {
		signals = signals[:3]
	}
	return signals
}

// computeRVol helper
func (s *ScannerAgent) computeRVol(token uint32) float64 {
	if s.ComputeRVol != nil {
		return s.ComputeRVol(token)
	}
	return 0.0
}

// ── Order Flow Intelligence ─────────────────────────────────────
// Uses real Kite 5-level depth data to score signal quality.
// Institutional desks call this "tape reading" — bid/ask imbalance
// reveals whether smart money is accumulating (buying) or distributing (selling).

// OrderFlowScore returns a multiplier (0.5 to 1.5) based on bid/ask imbalance.
// Values > 1.0 = order flow CONFIRMS the signal direction.
// Values < 1.0 = order flow is AGAINST the signal direction.
func (s *ScannerAgent) OrderFlowScore(token uint32, isShort bool) float64 {
	if s.GetDepth == nil {
		return 1.0 // No depth data, neutral score
	}

	depth := s.GetDepth(token)
	bidQty := depth["bid_qty"]
	askQty := depth["ask_qty"]

	if bidQty <= 0 && askQty <= 0 {
		return 1.0 // No depth data available
	}

	// Compute imbalance ratio: > 1 = more buyers, < 1 = more sellers
	var imbalance float64
	if askQty > 0 {
		imbalance = bidQty / askQty
	} else {
		imbalance = 2.0 // No sellers = extreme buying pressure
	}

	// For LONG signals: high bid/ask ratio confirms buying pressure
	// For SHORT signals: low bid/ask ratio confirms selling pressure
	if isShort {
		// Short wants selling pressure (low imbalance)
		if imbalance < 0.6 {
			return 1.3 // Strong selling pressure confirms short
		} else if imbalance < 0.8 {
			return 1.1 // Mild selling pressure
		} else if imbalance > 1.5 {
			return 0.7 // Buying pressure contradicts short
		}
	} else {
		// Long wants buying pressure (high imbalance)
		if imbalance > 1.5 {
			return 1.3 // Strong buying pressure confirms long
		} else if imbalance > 1.2 {
			return 1.1 // Mild buying pressure
		} else if imbalance < 0.6 {
			return 0.7 // Selling pressure contradicts long
		}
	}
	return 1.0 // Neutral
}

// MinNetProfitPerTrade is the minimum expected net profit after ALL charges.
// With ₹1L capital, position sizes are small — keep this low to allow trades through.
const MinNetProfitPerTrade = 5.0 // ₹5 minimum — just needs to cover charges

// FilterByNetProfit rejects signals whose expected profit at target doesn't cover charges.
// This single filter eliminates 60-70% of marginal trades that historically lost money.
func (s *ScannerAgent) FilterByNetProfit(signals []*Signal, capital float64) []*Signal {
	if len(signals) == 0 {
		return nil
	}

	var filtered []*Signal
	for _, sig := range signals {
		// Compute position size (risk-based): risk 0.5% of capital per trade
		risk := math.Abs(sig.EntryPrice - sig.StopPrice)
		if risk <= 0 {
			continue
		}
		maxRiskRs := capital * config.MaxRiskPerTradePct
		qty := int(maxRiskRs / risk)
		if qty <= 0 {
			qty = 1
		}

		// Compute expected gross profit at target
		var grossPnL float64
		if sig.IsShort {
			grossPnL = (sig.EntryPrice - sig.TargetPrice) * float64(qty)
		} else {
			grossPnL = (sig.TargetPrice - sig.EntryPrice) * float64(qty)
		}

		// Compute round-trip charges using centralized Zerodha charge function
		// Includes: brokerage (both sides), STT (sell only), stamp (buy only),
		//           exchange txn, SEBI, GST, IPFT + 0.1% slippage estimate
		totalCharges := core.ComputeChargesFromTrade(
			sig.EntryPrice, sig.TargetPrice, qty, sig.IsShort, "MIS", 0.001)

		netPnL := grossPnL - totalCharges

		if netPnL < MinNetProfitPerTrade {
			log.Printf("[ChargeFilter] REJECT %s %s: gross=%.0f charges=%.0f net=%.0f < min=%.0f (qty=%d)",
				sig.Strategy, sig.Symbol, grossPnL, totalCharges, netPnL, MinNetProfitPerTrade, qty)
			continue
		}

		sig.ExpectedNetPnL = netPnL
		sig.EstCharges = totalCharges
		sig.Qty = qty
		filtered = append(filtered, sig)
	}

	return filtered
}

// ══════════════════════════════════════════════════════════════
//  S10: GAP FILL STRATEGY
//  ~70% of opening gaps fill within 2 hours. One of the highest
//  win rate setups in equity markets.
// ══════════════════════════════════════════════════════════════
func (s *ScannerAgent) ScanS10GapFill(regime string) []*Signal {
	now := config.NowIST()
	hour, min := now.Hour(), now.Minute()
	t := hour*100 + min

	// Gap fill only works in first 2 hours: 09:16 - 11:00
	if t < 916 || t > 1100 || regime == "EXTREME_PANIC" || !s.cacheReady() || !s.checkDailyTradeLimit() {
		return nil
	}

	// Broad market direction filter: use AD ratio of 250-stock universe
	// instead of Nifty 50. AD ratio > 0.6 = market bullish, < 0.4 = market bearish
	adRatio := 0.5
	if s.GetADRatio != nil {
		a := s.GetADRatio()
		if a > 0 {
			adRatio = a
		}
	}

	var signals []*Signal
	for token, symbol := range s.Universe {
		current := s.GetLTP(token)
		if current <= 0 || current < 100 {
			continue
		}

		closes := s.DailyCache.Closes[token]
		if len(closes) < 5 {
			continue
		}
		prevClose := closes[len(closes)-1]
		if prevClose <= 0 {
			continue
		}

		dayOpen := 0.0
		if s.GetDayOpen != nil {
			dayOpen = s.GetDayOpen(token)
		}
		if dayOpen <= 0 {
			continue
		}

		gapPct := (dayOpen - prevClose) / prevClose * 100

		// Only trade significant gaps: 2.0% - 5% (too small = noise, too large = news-driven)
		if math.Abs(gapPct) < 2.0 || math.Abs(gapPct) > 5.0 {
			continue
		}

		rvol := s.computeRVol(token)
		if rvol < 1.0 {
			continue
		}

		atr := s.DailyCache.ATR[token]
		if atr <= 0 {
			atr = current * 0.015
		}

		// GAP UP → SHORT (fade the gap, target = prev close)
		if gapPct > 2.0 && current > prevClose*1.005 {
			// Don't fade gap-ups when broad market is strongly bullish
			if adRatio > 0.60 {
				continue
			}
			// RSI(14) confirmation: only short if RSI > 65 (overbought)
			// Skip before 10:00 — not enough 5-min candles for reliable RSI(14)
			if t >= 1000 {
				candles := s.getCandles5m(token)
				if len(candles) >= 14 {
					closes := make([]float64, len(candles))
					for ci, c := range candles { closes[ci] = c.Close }
					rsiSlice := data.ComputeRSI(closes, 14)
					if rsiSlice[len(rsiSlice)-1] < 65 {
						continue
					}
				}
			}
			// Price still above prev close, gap hasn't filled yet
			targetPrice := math.Round(prevClose*100) / 100
			stopPrice := math.Round((dayOpen+0.5*atr)*100) / 100
			risk := stopPrice - current
			if risk <= 0 {
				continue
			}

			signals = append(signals, &Signal{
				Strategy: "S10_GAP_FILL", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
				RVol: rvol, ATR: atr,
				Product: "MIS", IsShort: true, MaxHoldMins: 120,
				SortKey: math.Abs(gapPct),
			})
		}

		// GAP DOWN → LONG (fade the gap, target = prev close)
		if gapPct < -2.0 && current < prevClose*0.995 {
			// Don't fade gap-downs when broad market is strongly bearish
			if adRatio < 0.40 {
				continue
			}
			// RSI(14) confirmation: only buy if RSI < 35 (oversold)
			// Skip before 10:00 — not enough 5-min candles for reliable RSI(14)
			if t >= 1000 {
				candles := s.getCandles5m(token)
				if len(candles) >= 14 {
					closes := make([]float64, len(candles))
					for ci, c := range candles { closes[ci] = c.Close }
					rsiSlice := data.ComputeRSI(closes, 14)
					if rsiSlice[len(rsiSlice)-1] > 35 {
						continue
					}
				}
			}
			targetPrice := math.Round(prevClose*100) / 100
			stopPrice := math.Round((dayOpen-0.5*atr)*100) / 100
			risk := current - stopPrice
			if risk <= 0 {
				continue
			}

			signals = append(signals, &Signal{
				Strategy: "S10_GAP_FILL", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
				RVol: rvol, ATR: atr,
				Product: "MIS", IsShort: false, MaxHoldMins: 120,
				SortKey: math.Abs(gapPct),
			})
		}
	}

	sort.Slice(signals, func(i, j int) bool { return signals[i].SortKey > signals[j].SortKey })
	if len(signals) > 3 {
		signals = signals[:3]
	}
	return signals
}

// ══════════════════════════════════════════════════════════════
//  S11: VWAP MEAN REVERSION (Pure)
//  Most used institutional intraday strategy. When price deviates
//  >2 SD from VWAP, fade toward VWAP. Unlike S6 which is a
//  band-based trend strategy, this is pure reversion.
// ══════════════════════════════════════════════════════════════
func (s *ScannerAgent) ScanS11VWAPRevert(regime string) []*Signal {
	if !s.IsInTradeWindow() || !s.checkDailyTradeLimit() || regime == "EXTREME_PANIC" || !s.cacheReady() {
		return nil
	}
	// Best after initial volatility settles: 10:00+
	now := config.NowIST()
	if now.Hour()*100+now.Minute() < 1000 {
		return nil
	}

	var signals []*Signal
	for token, symbol := range s.Universe {
		current := s.GetLTP(token)
		if current <= 0 || current < 200 {
			continue
		}

		vwap := 0.0
		if s.GetVWAP != nil {
			vwap = s.GetVWAP(token)
		}
		if vwap <= 0 {
			continue
		}

		deviation := (current - vwap) / vwap
		absDevPct := math.Abs(deviation) * 100

		// Need significant deviation: >1.5% from VWAP
		if absDevPct < 1.5 {
			continue
		}

		rvol := s.computeRVol(token)
		if rvol < 1.0 {
			continue
		}

		// Reject if volume is EXTREMELY high (news event, don't fade)
		if rvol > 5.0 {
			continue
		}

		atr := s.DailyCache.ATR[token]
		if atr <= 0 {
			atr = current * 0.015
		}

		// RSI confirmation: oversold for long, overbought for short
		candles := s.getCandles5m(token)
		if len(candles) < 14 {
			continue
		}
		closes := make([]float64, len(candles))
		for i, c := range candles {
			closes[i] = c.Close
		}
		rsiSlice := data.ComputeRSI(closes, 14)
		rsi := rsiSlice[len(rsiSlice)-1]

		// LONG: Price far below VWAP + RSI oversold
		if deviation < -0.015 && rsi < 30 {
			targetPrice := math.Round((vwap-0.002*vwap)*100) / 100 // Target slightly below VWAP
			stopPrice := math.Round((current-0.8*atr)*100) / 100
			risk := current - stopPrice
			if risk <= 0 {
				continue
			}
			potential := targetPrice - current
			if potential < 1.5*risk {
				continue // Need R:R >= 1.5
			}

			signals = append(signals, &Signal{
				Strategy: "S11_VWAP_REVERT", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
				VWAP: vwap, RVol: rvol, RSI: rsi, ATR: atr,
				Product: "MIS", IsShort: false, MaxHoldMins: 90,
				SortKey: absDevPct,
			})
		}

		// SHORT: Price far above VWAP + RSI overbought
		if deviation > 0.015 && rsi > 70 {
			targetPrice := math.Round((vwap+0.002*vwap)*100) / 100
			stopPrice := math.Round((current+0.8*atr)*100) / 100
			risk := stopPrice - current
			if risk <= 0 {
				continue
			}
			potential := current - targetPrice
			if potential < 1.5*risk {
				continue
			}

			signals = append(signals, &Signal{
				Strategy: "S11_VWAP_REVERT", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
				VWAP: vwap, RVol: rvol, RSI: rsi, ATR: atr,
				Product: "MIS", IsShort: true, MaxHoldMins: 90,
				SortKey: absDevPct,
			})
		}
	}

	sort.Slice(signals, func(i, j int) bool { return signals[i].SortKey > signals[j].SortKey })
	if len(signals) > 3 {
		signals = signals[:3]
	}
	return signals
}

// ══════════════════════════════════════════════════════════════
//  S12: END-OF-DAY MEAN REVERSION
//  Between 14:00-14:50, stocks that have moved >2% from VWAP
//  tend to revert. Institutional profit-taking creates this window.
//  Very high win rate due to forced MIS squareoff pressure.
// ══════════════════════════════════════════════════════════════
func (s *ScannerAgent) ScanS12EODReversion(regime string) []*Signal {
	now := config.NowIST()
	hour, min := now.Hour(), now.Minute()
	t := hour*100 + min

	// Only 14:00 - 14:45
	if t < 1400 || t > 1445 || regime == "EXTREME_PANIC" || !s.cacheReady() || !s.checkDailyTradeLimit() {
		return nil
	}

	var signals []*Signal
	for token, symbol := range s.Universe {
		current := s.GetLTP(token)
		if current <= 0 || current < 200 {
			continue
		}

		vwap := 0.0
		if s.GetVWAP != nil {
			vwap = s.GetVWAP(token)
		}
		if vwap <= 0 {
			continue
		}

		deviation := (current - vwap) / vwap
		absDevPct := math.Abs(deviation) * 100

		// Need >2.5% deviation for EOD reversion
		if absDevPct < 2.5 {
			continue
		}

		atr := s.DailyCache.ATR[token]
		if atr <= 0 {
			atr = current * 0.015
		}

		rvol := s.computeRVol(token)
		// Low volume is actually GOOD for EOD reversion (means the move is exhausted)

		// RSI(14) confirmation for EOD reversion
		candles := s.getCandles5m(token)
		rsi := 50.0
		if len(candles) >= 14 {
			closes := make([]float64, len(candles))
			for ci, c := range candles { closes[ci] = c.Close }
			rsiSlice := data.ComputeRSI(closes, 14)
			rsi = rsiSlice[len(rsiSlice)-1]
		}

		// LONG: Stock beaten down >2.5% from VWAP in afternoon → snap back
		if deviation < -0.025 && rsi < 30 {
			targetPrice := math.Round((vwap-0.005*vwap)*100) / 100 // Partial fill toward VWAP
			stopPrice := math.Round((current-1.0*atr)*100) / 100 // Widened from 0.5 to 1.0 ATR
			risk := current - stopPrice
			if risk <= 0 {
				continue
			}

			signals = append(signals, &Signal{
				Strategy: "S12_EOD_REVERT", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
				VWAP: vwap, RVol: rvol, ATR: atr, RSI: rsi,
				Product: "MIS", IsShort: false, MaxHoldMins: 45,
				SortKey: absDevPct,
			})
		}

		// SHORT: Stock pumped >2.5% above VWAP → MIS squareoff will pull it down
		if deviation > 0.025 && rsi > 70 {
			targetPrice := math.Round((vwap+0.005*vwap)*100) / 100
			stopPrice := math.Round((current+1.0*atr)*100) / 100 // Widened from 0.5 to 1.0 ATR
			risk := stopPrice - current
			if risk <= 0 {
				continue
			}

			signals = append(signals, &Signal{
				Strategy: "S12_EOD_REVERT", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
				VWAP: vwap, RVol: rvol, ATR: atr, RSI: rsi,
				Product: "MIS", IsShort: true, MaxHoldMins: 45,
				SortKey: absDevPct,
			})
		}
	}

	sort.Slice(signals, func(i, j int) bool { return signals[i].SortKey > signals[j].SortKey })
	if len(signals) > 3 {
		signals = signals[:3]
	}
	return signals
}

// ══════════════════════════════════════════════════════════════
//  S13: RELATIVE STRENGTH SECTOR ROTATION
//  Buy the strongest stock in the strongest sector.
//  Short the weakest stock in the weakest sector.
//  Institutional alpha comes from sector-level momentum.
// ══════════════════════════════════════════════════════════════
func (s *ScannerAgent) ScanS13SectorRotation(regime string) []*Signal {
	if !s.IsInTradeWindow() || !s.checkDailyTradeLimit() || regime == "EXTREME_PANIC" || !s.cacheReady() {
		return nil
	}

	// Scan in 15-minute windows (first 30 seconds of each 15-min block)
	now := config.NowIST()
	minInBlock := now.Minute() % 15
	if minInBlock > 0 {
		return nil // Only scan during the first minute of each 15-min window
	}

	// Per-symbol cooldown: don't re-signal same stock within 2 hours
	// Prevents MRF/VEDL/TATASTEEL/ADANIPOWER spamming every 15 minutes

	// Compute intraday change for each symbol
	type symbolStrength struct {
		token    uint32
		symbol   string
		changePct float64
		rvol     float64
	}

	var allStocks []symbolStrength
	for token, symbol := range s.Universe {
		current := s.GetLTP(token)
		if current <= 0 || current < 200 { // Min price filter: no penny stocks
			continue
		}
		dayOpen := 0.0
		if s.GetDayOpen != nil {
			dayOpen = s.GetDayOpen(token)
		}
		if dayOpen <= 0 {
			continue
		}

		changePct := (current - dayOpen) / dayOpen * 100
		rvol := s.computeRVol(token)

		allStocks = append(allStocks, symbolStrength{
			token: token, symbol: symbol, changePct: changePct, rvol: rvol,
		})
	}

	if len(allStocks) < 20 {
		return nil
	}

	// Sort by change: strongest to weakest
	sort.Slice(allStocks, func(i, j int) bool { return allStocks[i].changePct > allStocks[j].changePct })

	var signals []*Signal

	// Top 3 strongest + high volume → LONG (momentum continuation)
	for i := 0; i < 3 && i < len(allStocks); i++ {
		ss := allStocks[i]
		if ss.changePct < 2.5 || ss.rvol < 1.5 {
			continue
		}

		// Per-symbol 2-hour cooldown: don't re-signal same stock
		if lastSig, ok := s.s13SignalCooldown[ss.symbol]; ok {
			if time.Since(lastSig) < 2*time.Hour {
				continue
			}
		}

		current := s.GetLTP(ss.token)
		atr := s.DailyCache.ATR[ss.token]
		if atr <= 0 {
			atr = current * 0.015
		}
		sma200 := s.DailyCache.SMA200[ss.token]
		if sma200 > 0 && current < sma200 {
			continue // Don't buy below 200SMA
		}

		// RSI(14) confirmation: only buy if RSI > 60 (momentum confirmed)
		candles := s.getCandles5m(ss.token)
		if len(candles) >= 14 {
			closes := make([]float64, len(candles))
			for ci, c := range candles { closes[ci] = c.Close }
			rsiSlice := data.ComputeRSI(closes, 14)
			if rsiSlice[len(rsiSlice)-1] < 60 {
				continue
			}
		}

		stopPrice := math.Round((current-0.5*atr)*100) / 100
		risk := current - stopPrice
		if risk <= 0 {
			continue
		}
		targetPrice := math.Round((current+2.5*risk)*100) / 100

		signals = append(signals, &Signal{
			Strategy: "S13_SECTOR_ROT", Symbol: ss.symbol, Token: ss.token, Regime: regime,
			EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
			RVol: ss.rvol, ATR: atr,
			Product: "MIS", IsShort: false, MaxHoldMins: 45,
			SortKey: ss.changePct * ss.rvol,
		})
		s.s13SignalCooldown[ss.symbol] = time.Now() // Record cooldown
	}

	// Bottom 3 weakest + high volume → SHORT (momentum continuation)
	for i := len(allStocks) - 1; i >= len(allStocks)-3 && i >= 0; i-- {
		ss := allStocks[i]
		if ss.changePct > -2.5 || ss.rvol < 1.5 {
			continue
		}

		// Per-symbol 2-hour cooldown: don't re-signal same stock
		if lastSig, ok := s.s13SignalCooldown[ss.symbol]; ok {
			if time.Since(lastSig) < 2*time.Hour {
				continue
			}
		}

		current := s.GetLTP(ss.token)
		atr := s.DailyCache.ATR[ss.token]
		if atr <= 0 {
			atr = current * 0.015
		}
		sma200 := s.DailyCache.SMA200[ss.token]
		if sma200 > 0 && current > sma200 {
			continue // Don't short above 200SMA
		}

		// RSI(14) confirmation: only short if RSI < 40 (weakness confirmed)
		candles := s.getCandles5m(ss.token)
		if len(candles) >= 14 {
			closes := make([]float64, len(candles))
			for ci, c := range candles { closes[ci] = c.Close }
			rsiSlice := data.ComputeRSI(closes, 14)
			if rsiSlice[len(rsiSlice)-1] > 40 {
				continue
			}
		}

		stopPrice := math.Round((current+0.5*atr)*100) / 100
		risk := stopPrice - current
		if risk <= 0 {
			continue
		}
		targetPrice := math.Round((current-2.5*risk)*100) / 100

		signals = append(signals, &Signal{
			Strategy: "S13_SECTOR_ROT", Symbol: ss.symbol, Token: ss.token, Regime: regime,
			EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
			RVol: ss.rvol, ATR: atr,
			Product: "MIS", IsShort: true, MaxHoldMins: 45,
			SortKey: math.Abs(ss.changePct) * ss.rvol,
		})
		s.s13SignalCooldown[ss.symbol] = time.Now() // Record cooldown
	}

	return signals
}

// ══════════════════════════════════════════════════════════════
//  S14: RSI SCALPER (RSI-2 on 5-min — Larry Connors Method)
//  RSI(2) is the most mean-reverting indicator on short timeframes.
//  When RSI(2) < 10, price is extremely oversold → buy the bounce.
//  When RSI(2) > 90, price is extremely overbought → short the fade.
//  VWAP acts as the only trend filter. NO RVol. NO ADX.
//  This is designed to FIRE signals, not sit idle.
// ══════════════════════════════════════════════════════════════
func (s *ScannerAgent) ScanS14RSIScalp(regime string) []*Signal {
	if !s.IsInTradeWindow() || !s.checkDailyTradeLimit() || regime == "EXTREME_PANIC" || !s.cacheReady() {
		return nil
	}

	var signals []*Signal
	for token, symbol := range s.Universe {
		current := s.GetLTP(token)
		if current <= 0 || current < config.S14_MIN_PRICE {
			continue
		}

		candles := s.getCandles5m(token)
		if len(candles) < 5 {
			continue
		}
		closes := make([]float64, len(candles))
		for i, c := range candles {
			closes[i] = c.Close
		}

		// RSI(2) — ultra-short period for scalping
		rsiSlice := data.ComputeRSI(closes, config.S14_RSI_PERIOD)
		if len(rsiSlice) == 0 {
			continue
		}
		rsi2 := rsiSlice[len(rsiSlice)-1]

		// VWAP trend filter (only filter we use)
		vwap := 0.0
		if s.GetVWAP != nil {
			vwap = s.GetVWAP(token)
		}

		atr := s.DailyCache.ATR[token]
		if atr <= 0 {
			atr = current * 0.015
		}

		// LONG: RSI(2) < 5 (extreme oversold) + price near or BELOW VWAP (buy the dip)
		vwapProximity := 0.0
		if vwap > 0 {
			vwapProximity = (current - vwap) / vwap
		}
		if rsi2 < float64(config.S14_RSI_OVERSOLD) && (vwap <= 0 || vwapProximity < 0.003) {
			stopPrice := math.Round(current*(1-config.S14_STOP_PCT)*100) / 100
			risk := current - stopPrice
			if risk <= 0 {
				continue
			}
			targetPrice := math.Round((current + 1.5*risk) * 100) / 100

			signals = append(signals, &Signal{
				Strategy: "S14_RSI_SCALP", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
				RSI: rsi2, VWAP: vwap, ATR: atr,
				Product: "MIS", IsShort: false, MaxHoldMins: config.S14_MAX_HOLD_MINS,
				SortKey: float64(config.S14_RSI_OVERSOLD) - rsi2, // Lower RSI = stronger signal
			})
		}

		// SHORT: RSI(2) > 95 (extreme overbought) + price near or ABOVE VWAP (short the pump)
		if rsi2 > float64(config.S14_RSI_OVERBOUGHT) && (vwap <= 0 || vwapProximity > -0.003) {
			stopPrice := math.Round(current*(1+config.S14_STOP_PCT)*100) / 100
			risk := stopPrice - current
			if risk <= 0 {
				continue
			}
			targetPrice := math.Round((current - 1.5*risk) * 100) / 100

			signals = append(signals, &Signal{
				Strategy: "S14_RSI_SCALP", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice, TargetPrice: targetPrice,
				RSI: rsi2, VWAP: vwap, ATR: atr,
				Product: "MIS", IsShort: true, MaxHoldMins: config.S14_MAX_HOLD_MINS,
				SortKey: rsi2 - float64(config.S14_RSI_OVERBOUGHT), // Higher RSI = stronger signal
			})
		}
	}

	sort.Slice(signals, func(i, j int) bool { return signals[i].SortKey > signals[j].SortKey })
	if len(signals) > 5 {
		signals = signals[:5]
	}
	return signals
}

// ══════════════════════════════════════════════════════════════
//  S15: RSI SWING (RSI-14 Pullback + EMA20 Trend Confirmation)
//  Buy pullbacks in uptrends, short pullbacks in downtrends.
//  RSI(14) < 35 in an uptrend (price > EMA20) = classic dip buy.
//  RSI(14) > 65 in a downtrend (price < EMA20) = classic rally short.
//  Simple. Proven. High win rate on liquid stocks.
// ══════════════════════════════════════════════════════════════
func (s *ScannerAgent) ScanS15RSISwing(regime string) []*Signal {
	if !s.IsInTradeWindow() || !s.checkDailyTradeLimit() || regime == "EXTREME_PANIC" || !s.cacheReady() {
		return nil
	}

	var signals []*Signal
	for token, symbol := range s.Universe {
		current := s.GetLTP(token)
		if current <= 0 || current < config.S15_MIN_PRICE {
			continue
		}

		candles := s.get15MinOHLC(token)
		if len(candles) < config.S15_EMA_TREND+2 {
			continue
		}

		closes := make([]float64, len(candles))
		highs := make([]float64, len(candles))
		lows := make([]float64, len(candles))
		for i, c := range candles {
			closes[i] = c.Close
			highs[i] = c.High
			lows[i] = c.Low
		}

		// EMA20 trend filter on 15-min
		ema20 := data.ComputeEMA(closes, config.S15_EMA_TREND)
		if len(ema20) == 0 {
			continue
		}
		emaVal := ema20[len(ema20)-1]

		// RSI(14) on 15-min
		rsiSlice := data.ComputeRSI(closes, config.S15_RSI_PERIOD)
		if len(rsiSlice) == 0 {
			continue
		}
		rsi14 := rsiSlice[len(rsiSlice)-1]

		atr := s.DailyCache.ATR[token]
		if atr <= 0 {
			atr = current * 0.02
		}

		// LONG: Price > EMA20 (uptrend) + RSI < 35 (pullback/oversold)
		if current > emaVal && rsi14 < float64(config.S15_RSI_OVERSOLD) {
			stopPrice := math.Round((current - config.S15_ATR_SL_MULT*atr) * 100) / 100
			risk := current - stopPrice
			if risk <= 0 {
				continue
			}
			targetPrice := math.Round((current + config.S15_RR*risk) * 100) / 100

			signals = append(signals, &Signal{
				Strategy: "S15_RSI_SWING", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice,
				PartialTarget: math.Round((current + 1.0*risk) * 100) / 100,
				TargetPrice: targetPrice, RSI: rsi14, ATR: atr,
				Product: "MIS", IsShort: false, MaxHoldMins: config.S15_MAX_HOLD_MINS,
				SortKey: float64(config.S15_RSI_OVERSOLD) - rsi14,
			})
		}

		// SHORT: Price < EMA20 (downtrend) + RSI > 65 (rally/overbought)
		if current < emaVal && rsi14 > float64(config.S15_RSI_OVERBOUGHT) {
			stopPrice := math.Round((current + config.S15_ATR_SL_MULT*atr) * 100) / 100
			risk := stopPrice - current
			if risk <= 0 {
				continue
			}
			targetPrice := math.Round((current - config.S15_RR*risk) * 100) / 100

			signals = append(signals, &Signal{
				Strategy: "S15_RSI_SWING", Symbol: symbol, Token: token, Regime: regime,
				EntryPrice: current, StopPrice: stopPrice,
				PartialTarget: math.Round((current - 1.0*risk) * 100) / 100,
				TargetPrice: targetPrice, RSI: rsi14, ATR: atr,
				Product: "MIS", IsShort: true, MaxHoldMins: config.S15_MAX_HOLD_MINS,
				SortKey: rsi14 - float64(config.S15_RSI_OVERBOUGHT),
			})
		}
	}

	sort.Slice(signals, func(i, j int) bool { return signals[i].SortKey > signals[j].SortKey })
	if len(signals) > 5 {
		signals = signals[:5]
	}
	return signals
}

// ══════════════════════════════════════════════════════════════
//  REGIME-BASED STRATEGY ROUTER (3-STATE MODEL)
//  BULLISH  = trend + momentum (market is clearly up)
//  BEARISH  = shorts + mean reversion (market is clearly down)
//  SIDEWAYS = ALL strategies (most common — let signals compete)
// ══════════════════════════════════════════════════════════════
func getStrategiesForRegime(regime string) []string {
	switch regime {
	case "BULLISH":
		// 🟢 Market is up: trend-following + momentum + breakouts
		return []string{
			"S1_MA_CROSS",      // EMA crossover — rides the uptrend
			"S3_ORB",           // ORB — breakouts extend in trending markets
			"S8_VOL_PIVOT",     // Volume pivot — breakout confirmation
			"S9_MTF_MOMENTUM",  // Multi-TF momentum — strongest in trends
			"S10_GAP_FILL",     // Gap fill — universal
			"S13_SECTOR_ROT",   // Sector rotation — buy the strongest
			"S14_RSI_SCALP",    // RSI scalp — universal
			"S15_RSI_SWING",    // RSI swing — pullback buying in uptrend
		}

	case "BEARISH":
		// 🔴 Market is down: shorts + mean reversion for oversold bounces
		return []string{
			"S2_BB_MEAN_REV",   // BB mean reversion — catch oversold bounces
			"S6_TREND_SHORT",   // Trend short — ride relative weakness
			"S6_VWAP_BAND",     // VWAP band — reversion from extremes
			"S10_GAP_FILL",     // Gap fill — gap-downs fill frequently
			"S13_SECTOR_ROT",   // Sector rotation — short weakest
			"S14_RSI_SCALP",    // RSI scalp — extremes in panic = scalps
			"S15_RSI_SWING",    // RSI swing — oversold bounce plays
		}

	default: // "SIDEWAYS" and any other value
		// 🟡 No clear direction — ALL strategies compete for best signals
		// This is the most common state. The engine should trade freely here.
		return []string{
			"S1_MA_CROSS",
			"S2_BB_MEAN_REV",
			"S3_ORB",
			"S6_VWAP_BAND",
			"S7_MEAN_REV_LONG",
			"S8_VOL_PIVOT",
			"S9_MTF_MOMENTUM",
			"S10_GAP_FILL",
			"S11_VWAP_REVERT",
			"S12_EOD_REVERT",
			"S13_SECTOR_ROT",
			"S14_RSI_SCALP",
			"S15_RSI_SWING",
		}
	}
}

// RunAllScans executes all strategies and returns combined signals
// FILTERED by net profitability — no signal reaches execution unless it
// can produce ≥₹50 net profit after ALL Zerodha charges.
func (s *ScannerAgent) RunAllScans(regime string) []*Signal {
	// Last entry time enforcement: allow trades until 15:00 for late-day setups
	if !s.SimulatorMode {
		now := config.NowIST()
		t := now.Hour()*100 + now.Minute()
		if t > 1500 {
			return nil
		}
	}
	return s.RunStrategyScans(regime, nil)
}

// RunStrategyScans executes specific strategies by string name. 
// If strategies is nil or empty, uses REGIME-BASED ROUTING to select appropriate strategies.
// If strategies are explicitly specified (e.g., by backtester), runs exactly those.
func (s *ScannerAgent) RunStrategyScans(regime string, strategies []string) []*Signal {
	var all []*Signal

	// Full strategy registry
	strategyMap := map[string]func(string) []*Signal{
		"S1_MA_CROSS":       s.ScanS1,              // EMA crossover — trend-following
		"S2_BB_MEAN_REV":    s.ScanS2,              // Bollinger mean reversion
		"S3_ORB":            s.ScanS3,              // ORB — breakout setup
		"S6_TREND_SHORT":    s.ScanS6TrendShort,    // Relative weakness short
		"S6_VWAP_BAND":      s.ScanS6VWAP,          // VWAP band reversion
		"S7_MEAN_REV_LONG":  s.ScanS7,              // Mean reversion long
		"S8_VOL_PIVOT":      s.ScanS8,              // Volume pivot breakout
		"S9_MTF_MOMENTUM":   s.ScanS9,              // Multi-timeframe momentum
		"S10_GAP_FILL":      s.ScanS10GapFill,      // Gap fill — 70% statistical edge
		"S11_VWAP_REVERT":   s.ScanS11VWAPRevert,   // Pure VWAP reversion
		"S12_EOD_REVERT":    s.ScanS12EODReversion, // EOD institutional reversion
		"S13_SECTOR_ROT":    s.ScanS13SectorRotation, // Sector rotation momentum
		"S14_RSI_SCALP":     s.ScanS14RSIScalp,     // RSI-2 Connors scalper
		"S15_RSI_SWING":     s.ScanS15RSISwing,     // RSI-14 pullback swing
	}

	// Helper to track which strategies actually ran for diagnostics
	runCounts := make(map[string]int)

	// Determine which strategies to run
	var toRun []string
	if len(strategies) == 0 {
		// ═══ REGIME-BASED STRATEGY ROUTING ═══
		// Different market conditions need different trading approaches.
		// Momentum strategies THRIVE in trends but get KILLED in chop.
		// Mean reversion strategies LOVE volatility but FAIL in strong trends.
		// Running the wrong strategies in the wrong regime = guaranteed losses.
		toRun = getStrategiesForRegime(regime)
		log.Printf("[Router] Regime=%s → %d strategies active: %v", regime, len(toRun), toRun)
	} else {
		// Explicit strategy list (from backtester/simulator) — run exactly those
		for _, name := range strategies {
			if _, exists := strategyMap[name]; exists {
				toRun = append(toRun, name)
			} else {
				log.Printf("[Scanner] Warning: Unknown strategy requested: %s (skipping)", name)
			}
		}
	}

	// Execute matched strategies
	for _, name := range toRun {
		scanFunc := strategyMap[name]
		sigs := scanFunc(regime)
		all = append(all, sigs...)
		runCounts[name] = len(sigs)
	}

	// Catch-all to populate missing ML prerequisites for ANY strategy
	for _, sig := range all {
		if sig.RSI == 0 || sig.ADX == 0 || sig.RVol == 0 {
			if sig.RVol == 0 && s.ComputeRVol != nil {
				sig.RVol = s.ComputeRVol(sig.Token)
			}

			candles := s.getCandles5m(sig.Token)
			if len(candles) >= 15 {
				closes := make([]float64, len(candles))
				highs := make([]float64, len(candles))
				lows := make([]float64, len(candles))
				for i, c := range candles {
					closes[i] = c.Close
					highs[i] = c.High
					lows[i] = c.Low
				}

				if sig.RSI == 0 {
					rsiSlice := data.ComputeRSI(closes, 14)
					sig.RSI = rsiSlice[len(rsiSlice)-1]
				}
				if sig.ADX == 0 {
					sig.ADX = data.ComputeADX(highs, lows, closes, 14)
				}
			} else if sig.RSI == 0 {
				sig.RSI = 50.0 // Neutral fallback if data is missing
			}
		}
	}

	// ═══ ALWAYS-ON DIAGNOSTICS (every 30s) ═══
	now := config.NowIST()
	if now.Second() == 0 || now.Second() == 30 {
		ltpCount := 0
		candleCount := 0
		for token := range s.Universe {
			if s.GetLTP != nil && s.GetLTP(token) > 0 {
				ltpCount++
			}
			if c := s.getCandles5m(token); len(c) >= 2 {
				candleCount++
			}
		}
		log.Printf("[DIAG] Universe=%d LTP_active=%d Candles5m≥2=%d CacheReady=%v InWindow=%v Regime=%s",
			len(s.Universe), ltpCount, candleCount, s.cacheReady(), s.IsInTradeWindow(), regime)
		
		// Map the run counts appropriately for the live engine to see familiar output
		log.Printf("[DIAG] RAW: S1=%d S2=%d S3=%d S6T=%d S6V=%d S7=%d S8=%d S9=%d S10=%d S11=%d S12=%d S13=%d S14=%d S15=%d TOTAL=%d",
			runCounts["S1_MA_CROSS"], runCounts["S2_BB_MEAN_REV"], runCounts["S3_ORB"], 
			runCounts["S6_TREND_SHORT"], runCounts["S6_VWAP_BAND"], runCounts["S7_MEAN_REV_LONG"], 
			runCounts["S8_VOL_PIVOT"], runCounts["S9_MTF_MOMENTUM"], runCounts["S10_GAP_FILL"], 
			runCounts["S11_VWAP_REVERT"], runCounts["S12_EOD_REVERT"], runCounts["S13_SECTOR_ROT"], 
			runCounts["S14_RSI_SCALP"], runCounts["S15_RSI_SWING"], len(all))
	}

	// ═══ MINIMUM R:R ENFORCEMENT (structural fix for inverted R:R) ═══
	// Historical data: avg loss = 2.7× avg win. This rejects signals where
	// reward < 1.5× risk, ensuring positive expectancy at any win rate > 40%.
	var rrFiltered []*Signal
	for _, sig := range all {
		var risk, reward float64
		if sig.IsShort {
			risk = sig.StopPrice - sig.EntryPrice
			reward = sig.EntryPrice - sig.TargetPrice
		} else {
			risk = sig.EntryPrice - sig.StopPrice
			reward = sig.TargetPrice - sig.EntryPrice
		}
		if risk <= 0 {
			continue
		}
		rr := reward / risk
		if rr < config.MinRR {
			log.Printf("[RR_FILTER] REJECTED %s %s R:R=%.2f (min=%.1f) reward=%.1f risk=%.1f",
				sig.Strategy, sig.Symbol, rr, config.MinRR, reward, risk)
			continue
		}
		rrFiltered = append(rrFiltered, sig)
	}
	if len(all) > 0 && len(rrFiltered) < len(all) {
		log.Printf("[Scanner] R:R filter: %d/%d passed (rejected %d with R:R < %.1f)",
			len(rrFiltered), len(all), len(all)-len(rrFiltered), config.MinRR)
	}

	// Filter by net profitability — reject signals that can't cover charges
	filtered := s.FilterByNetProfit(rrFiltered, config.TotalCapital)

	if len(rrFiltered) > 0 && len(filtered) < len(rrFiltered) {
		log.Printf("[Scanner] Charge filter: %d/%d signals passed (rejected %d unprofitable)",
			len(filtered), len(rrFiltered), len(rrFiltered)-len(filtered))
	}

	return filtered
}
